### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#1013]
Python 3.11 provides major performance improvement that I would like to take advantage of when using the HoloViz ecosystem.

Panel and HoloViews already support python 3.11 according to Pypi.

Please support python 3.11. Thanks.

**Comment by maximlt** [comment]
Did you encounter any issue running hvPlot on Python 3.11?

**Comment by MarcSkovMadsen** [comment]
I have not tried as it's not mentioned as supported.

**Comment by maximlt** [comment]
That doesn't mean it's unsupported :) We made sure hvPlot was working with Python 3.11 a while ago. It does as is and this means that it doesn't need a release, just not for that at least.

**Comment by MarcSkovMadsen** [comment]
The issue is that if you go to pupils 3.11 is not listed as supported
