### ISSUE TITLE
Addition of FAQ section on the official website of hvPlot website

### ISSUE THREAD

**Issue by DevanshRaizada** [holoviz/hvplot#1059]
The FAQ section is missing on the [hvPlot](https://hvplot.holoviz.org/index.html) library website and the addition of the section would be of great help to all the users

#### Is your feature request related to a problem? Please describe.
Basic questions like ''What objects can I use hvPlot with?'' can be answered very easily

#### Describe the solution you'd like
A FAQ section covering all the fundamental question that comes to one's mind in the first place.

#### Additional context
An FAQ section is a vital section of any product website and is been missing on the hvPlot website.
If given a chance I would love to contribute on this issue..

**Comment by maximlt** [comment]
Closing as duplicate of https://github.com/holoviz/hvplot/issues/1060
