### ISSUE TITLE
Create a Fugue integration similar to ipyvizzu

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1097]
I was talking to Fugue maintainers (@goodwanghan) and they suggested we could do something like:
https://github.com/vizzuhq/ipyvizzu/blob/main/src/ipyvizzu/integrations/fugue.py

so users can do something like:
```
LOAD "....csv"(header=TRUE,infer_schema=TRUE)
SELECT * FROM df WHERE name == "KATRINA" AND season == 2005
OUTPUT USING hvplot:points(x="LON",
        y="LAT",
        color="USA_WIND",
        hover_cols=["NAME", "LAT", "LON", "ISO_TIME", "USA_WIND",     "USA_PRES"],
        tiles=TRUE,
        geo=TRUE,
        cmap="Reds")
```

I imagine a separate module named `fugue.py` under https://github.com/holoviz/hvplot/tree/main/hvplot

Looks fairly straightforward and happy to implement if accepted

**Comment by goodwanghan** [comment]
With this integration, hvplot will be connected with spark sql, bigquery, trino, and soon snowflake (when we release the snowflake integration)

Here is an example on bigquery: https://www.linkedin.com/search/results/content/?keywords=ipyvizzu%20bigquery&sid=s8r&update=urn%3Ali%3Afs_updateV2%3A(urn%3Ali%3Aactivity%3A7039309444190523392%2CBLENDED_SEARCH_FEED%2CEMPTY%2CDEFAULT%2Cfalse)
