### ISSUE TITLE
shared_axes=False not working for hvplot.hist()

### ISSUE THREAD

**Issue by JanHomann** [holoviz/hvplot#1100]
## Versions
bokeh         3.1.1
holoviews     1.16.2
hvplot        0.8.4

## Issue
The plotting parameter `shared_axes=False` in the function `.hvplot.hist()`, when using `subplots=True`, does not lead to a rescaling of the x-axis for the individual subplots to accommodate the data. Instead the plots keeps having the same x-scale. Other plot types seem to work, so the issue seems specific to `.hist()`.

## Code

```
import hvplot.pandas
from hvplot.sample_data import us_crime

us_crime.hvplot.hist(subplots=True, shared_axes=False,
                     width=300, height=200)

```

## Screenshot of output of code demostrating the problematic behavior.
Each plot is scaled equally, and most end up having only one bin with data.

![171f6cc1840f74d65f96411045e88c96c9f8a6a9](https://github.com/holoviz/hvplot/assets/35338267/81b5df72-2efd-4e94-ab0d-c22457200395)

**Comment by heikone** [comment]
Can confirm this behavior.
Just started to use hvplot and exactly this was one of my first plots... 🫣
Would appreciate a solution or a workaround.

Greetings,
Heiko

**Comment by xuJ14** [comment]
Any updates?

**Comment by ahuang11** [comment]
Thanks for bumping; I think I have a fix in https://github.com/holoviz/hvplot/pull/1391

**Comment by xuJ14** [comment]
Thank you!
