### ISSUE TITLE
Add `threshold` kwarg; show individual points when zoomed; else datashade

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1101]
Can there be a `threshold` kwarg;
```python
df.hvplot("x", "y", rasterize=True, threshold=5000)
```

That does this:
```python
import holoviews as hv

from holoviews.operation.datashader import rasterize
from holoviews.operation import apply_when

points = hv.Points(np.random.randn(100000, 2))

apply_when(points, operation=rasterize, predicate=lambda x: len(x) > 5000)
```

https://discourse.holoviz.org/t/show-individual-points-when-zoomed-else-datashade/2204/5?u=ahuang11

**Comment by jbednar** [comment]
Yes, see https://github.com/holoviz/holoviews/issues/1076 . I think it would need to be `rasterize_threshold` or `count_limit` or `data_size_limit`, since `threshold` could mean just about anything.

**Comment by ahuang11** [comment]
To be clear, this would be in HoloViews or hvplot, or both?

**Comment by jbednar** [comment]
The keyword as discussed here would be in hvplot. I'd like the same functionality available as a HoloViews option, but don't know how other HoloViews devs feel about that.
