### ISSUE TITLE
hvplot setting xlim/ylim should first sel data when rasterize=True/datashade=True

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1120]
We can make an optimization in hvplot; namely, if ylim is provided like...

16 seconds
```
t = time.perf_counter()
display(ds.hvplot("lon", "lat", rasterize=True, ylim=(26, 30)))
elapsed = time.perf_counter() - t
print(f"Elapsed time: {elapsed:0.4f} seconds")
```

To something similar:

3 seconds
```
t = time.perf_counter()
display(ds.sel(lat=slice(30, 26)).hvplot("lon", "lat", rasterize=True))
elapsed = time.perf_counter() - t
print(f"Elapsed time: {elapsed:0.4f} seconds")
```

https://discourse.holoviz.org/t/fast-visualization-of-large-datasets-without-saving-to-disk-using-hvplot-kerchunk-and-datashader/5751/2?u=ahuang11

**Comment by philippjfr** [comment]
I agree with this, in hvPlot we have the benefit that data and plotting operations can be combined and thereby optimize the rendering experience. The only concern here is that xlim/ylim only determine the initial extent and when you zoom/pan you expect the rest of the data to be revealed. However I think this could be solved by providing xlim/ylim as inputs to x_range/y_range on the rasterize or other resampling operation.
