### ISSUE TITLE
datashade kwarg for scatter_matrix

### ISSUE THREAD

**Issue by timothydmorton** [holoviz/hvplot#114]
It would be nifty to have `datashade=True` work for the `scatter_matrix` function.  I'm happy to contribute this if someone can point me in the right direction.

**Comment by philippjfr** [comment]
The latest implementation might just look like this: 

```python
grid = grid.apply(datashade,  per_element=True)
```

**Comment by tlmille2** [comment]
Adding rasterize=True as an optional arg would be nice for large datasets.
