### ISSUE TITLE
Using hvplot.explorer as method instead of a function?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1153]
I'm used to using hvplot like
```python
df.hvplot.scatter()
```
or
```python
ds.hvplot.contourf()
```

At the moment, to use explorer, one would need to do
```python
hvplot.explorer(df)
```
I'd like to do this instead:
```python
df.hvplot.explorer()
```

**Comment by maximlt** [comment]
@philippjfr that looks like a good idea, is there a reason why it wasn't done in the first place?

**Comment by ahuang11** [comment]
My thought is that it has some circular dependencies (e.g. converter -> ui -> converter)

**Comment by philippjfr** [comment]
Seems like a nice idea. An inline import to make that work doesn't seem so bad.
