### ISSUE TITLE
Website issue with Explorer

### ISSUE THREAD

**Issue by jbednar** [holoviz/hvplot#1189]
<img width="1036" alt="image" src="https://github.com/holoviz/hvplot/assets/1695496/d629941f-1657-4c64-8cb6-511d2569240a">

**Comment by ahuang11** [comment]
I believe the issue is a width set.
https://github.com/holoviz/hvplot/blob/main/hvplot/ui.py#L453

I remember some overlapping issues if it's not set, but maybe I can reduce it a teeny bit.

**Comment by maximlt** [comment]
Improved by various recent changes made to the explorer:
<img width="1120" alt="image" src="https://github.com/holoviz/hvplot/assets/35924738/a9051324-8d3f-4950-8ef6-985779f97d75">
