### ISSUE TITLE
hvplot.ohlc() doesn't respect the hover_cols param

### ISSUE THREAD

**Issue by vanheck** [holoviz/hvplot#1214]
Hi, when use `hvplot.ohlc()` with user defined hover, the additional columns specified in `hover_cols` params doesn't appear in the result ColumnDataSource.

Source of this problem in stackoverflow: https://stackoverflow.com/questions/77631385/how-to-add-data-into-hover-in-hvplot-bokeh-candlestick-without-missing-date-ga

#### ALL software version info
python 3.12
bokeh 3.3.2
hvplot 0.9.0
holoviews 1.18.1

#### Complete, minimal, self-contained example code that reproduces the issue

```py
import pandas as pd
import hvplot.pandas

data = pd.DataFrame({
        "Open": [100.00, 101.25, 102.75],
        "High": [104.10, 105.50, 110.00],
        "Low": [94.00, 97.10, 99.20],
        "Close": [101.15, 99.70, 109.50],
        "Volume": [10012, 5000, 18000],
    }, index=[pd.Timestamp("2022-08-01"), pd.Timestamp("2022-08-03"), pd.Timestamp("2022-08-04")])

df = pd.DataFrame(data)

# fix hover ------
from bokeh.models import HoverTool

hover = HoverTool(
    tooltips=[
        ('Date', '@Date{%Y-%m-%d}'),
        ('Open', '@Open{0.00}'),
        ('High', '@High{0.00}'),
        ('Low', '@Low{0.00}'),
        ('Close', '@Close{0.00}'),
        ('Volume', '@Volume{0}'),
    ],
    formatters={'@Date': 'datetime'},
    mode='vline'
)
# fix hover ------

ohlc_cols = ["Open", "High", "Low", "Close"]
df.hvplot.ohlc(y=ohlc_cols, hover_cols=["Date", *ohlc_cols, "Volume"], tools=[hover])
```

#### Screenshot
![obrazek](https://github.com/holoviz/hvplot/assets/9953249/fc98717f-4401-489e-a99b-c8d5f2ca5e56)

**Comment by maximlt** [comment]
Fixed by https://github.com/holoviz/hvplot/pull/1216
