### ISSUE TITLE
Hvplot row not working

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/hvplot#1220]
#### ALL software version info
```
bokeh==3.3.2
holoviews==1.18.1
hvplot==0.9.0
jupyterlab==4.0.9
jupyterlab-widgets==3.0.9
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.2
```

```
Python 3.10.12
```

See details here: 

https://discourse.holoviz.org/t/hvplot-row-not-working/6621

**Comment by Hoxbro** [comment]
Likely the same issue as https://github.com/holoviz/hvplot/issues/937 and https://github.com/holoviz/holoviews/issues/5438.

**Comment by maximlt** [comment]
I agree it's a duplicate, closing in favor of https://github.com/holoviz/holoviews/issues/5438.
