### ISSUE TITLE
Document polars in reference guide?

### ISSUE THREAD

**Issue by MarcoGorelli** [holoviz/hvplot#1237]
#### Is your feature request related to a problem? Please describe.

hvplot works really well with polars (as far as I've tried taking it at least) but it barely seems mentioned in the docs

In particular, I'm struggling a bit with which page to link to in https://github.com/pola-rs/polars/pull/13238

#### Describe the solution you'd like

Maybe a Polars section would be added here
https://hvplot.holoviz.org/reference/index.html#pandas
?

Or the existing pandas one would be renamed "pandas and polars"?

**Comment by maximlt** [comment]
Hey @MarcoGorelli, yep you're right this heading should definitely be updated to be more inclusive to the [tabular data sources](https://hvplot.holoviz.org/user_guide/Integrations.html#columnar-tabular) hvplot integrates with. With something as simple as `tabular` or a more explicitly listing pandas/polars/ibis/cudf/etc. Depending on what is chosen, we may have to slightly modify [our sphinx gallery extension](https://github.com/holoviz-dev/nbsite/blob/main/nbsite/gallery/gen.py) to give us the freedom to modify the heading text (IIRC currently it's just the folder name formatted as a title), but that should be straightforward.

Generally, there's plenty of work to do to improve hvPlot's documentation, that's definitely something I want to push for the coming year, in particular the reference/visual API.

(I know you've pinged me on another issue on your repo, I'll get back to you early in January 🎅 )
