### ISSUE TITLE
y=None doesn't work for Polars dataframes

### ISSUE THREAD

**Issue by kevinheavey** [holoviz/hvplot#1246]
#### ALL software version info
```
>>> import hvplot
>>> hvplot.__version__
'0.9.1'
>>> import holoviews
>>> holoviews.__version__
'1.18.1'
>>> import polars
>>> polars.__version__
'0.20.3'
```

#### Description of expected behavior and the observed behavior

If you call, say `df.plot.line(x="foo")`, the docs say that all other numeric cols should be used as y values, but instead we get no plot and the following message: `matplotlib backend could not plot any Elements in the Overlay.`

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import polars as pl
pl.DataFrame({"a": [1, 2], "b": [3, 4]}).plot.line(x="a")
```

In the [_get_converter](https://github.com/holoviz/hvplot/blob/734c0cc922152ea6a0f3332bc2bf19f5430d7629/hvplot/plotting/core.py#L1867) method of hvPlotTabularPolars, we see that (if hover_cols is not set to "all") only columns from `x`, `y` and `kwds` will be selected:
```python
                possible_columns = [
                    [v] if isinstance(v, str) else v
                    for v in params.values()
                    if isinstance(v, (str, list))
                ]
                columns = (
                    set(self._data.columns) & set(itertools.chain(*possible_columns))
                ) or {self._data.columns[0]}
                xs = x if is_list_like(x) else (x,)
                ys = y if is_list_like(y) else (y,)
                columns |= {*xs, *ys}
                columns.discard(None)
```

### Proposed solution

When the y value is not specified, select all numeric columns (plus whatever is specified) in _get_converter. We can do this in Polars like this:

```python
import polars as pl
pl.DataFrame({"a": [1, 2], "b": [3, 4], "c": ["foo", "bar"], "d": ["ping", "pong"]}).select([pl.col("d"), pl.col(pl.NUMERIC_DTYPES)])
```
This code will select columns d, a and b.

There is still some filtering based on pandas dtype later in the code but I think this is applied to non-Polars sources too, so we may as well just leave it as it is for now.

- [x] I may be interested in making a pull request to address this

**Comment by braaannigan** [comment]
@kevinheavey Will the PR address this issue where layered or subplots also do not display e.g.
```python
pl.DataFrame({"x":[1,2],"y1":[3,4],"y2":[4,4]}).plot.bar(x="x",y=["y1","y2"])
```
or (as subplots)
```python
pl.DataFrame({"x":[1,2],"y1":[3,4],"y2":[4,4]}).plot.bar(x="x",y=["y1","y2"],subplots=True)
```

**Comment by Hoxbro** [comment]
@braaannigan both of these look fine to me:

![image](https://github.com/holoviz/hvplot/assets/19758978/1fd5e04c-676b-4e03-8093-f82fe3a92b13)

If you are still having a problem, can you please open a new issue?

**Comment by braaannigan** [comment]
> @braaannigan both of these look fine to me:
> 
> ![image](https://private-user-images.githubusercontent.com/19758978/296692880-1fd5e04c-676b-4e03-8093-f82fe3a92b13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDk5NDIsIm5iZiI6MTcwNTMwOTY0MiwicGF0aCI6Ii8xOTc1ODk3OC8yOTY2OTI4ODAtMWZkNWUwNGMtNjc2Yi00ZTAzLTgwOTMtZjgyZmUzYTkyYjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExM2M2YzA3MjY5MjQzMTkyMTk3ZmExYzE5ZmM0ODI1MWJkZTFjY2MxOGMzNjBlYTg2NTE5NTJiZGIxNjY0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mICJGCtxAJX5lTZBvrn-htHfrocCPs-GV45u-khe9OM)
> 
> If you are still having a problem, can you please open a new issue?

Apologies, seems like it's a problem with my notebook as none of my charts are rendering now.
