### ISSUE TITLE
`robust` or `clim_percentile` option to get the 2nd / 98th percentile 

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1251]
```python
from pystac_client import Client
from odc.stac import load
import numpy as np

client = Client.open("https://earth-search.aws.element84.com/v1")
collection = "sentinel-2-l2a"
tas_bbox = [146.5, -43.6, 146.7, -43.4]
search = client.search(collections=[collection], bbox=tas_bbox, datetime="2023-12")

ds = load(search.items(), bbox=tas_bbox, groupby="solar_day", chunks={})
da = ds[["red", "green", "blue"]].isel(time=2).load().to_array()
da.plot.imshow(robust=True)
```

<img width="717" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/cde2fe18-c239-4b66-a52b-7dd4d6f2cc59">

Without robust:
<img width="705" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/b74e4644-c0db-4542-9279-df6061c9b851">

Which is what hvplot yields.
<img width="924" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/c453b781-a433-4252-8b32-f1d29ddff8cd">

When I try to manually calculate it and pass a custom `clim`, there's no effect
https://github.com/pydata/xarray/blob/492aa076bd1812af71d68dc221312fb9a199d2d3/xarray/plot/utils.py#L215-L225

**Comment by maximlt** [comment]
HoloViews has the `clim_percentile` plot option but that only applies to plot types that inherit from `ColorbarPlot`, while `RGBPlot` inherits from `LegendPlot`. @ahuang11 I'd say we should first add this plot option to HoloViews? To eventually expose it in hvPlot, where I'd say `robust` would be a good choice given that `robust=True` would be already familiar to Xarray users.

**Comment by ahuang11** [comment]
I was looking at https://github.com/holoviz/holoviews/blob/6aa6c9ddb7c9308531753efae41cbd0873c975a3/holoviews/plotting/bokeh/raster.py#L134 and I'm not sure there's a way to add clim_percentile to RGBPlot without updating Bokeh too.

I tried doing:
```python     
        if self.clim_percentile:
            low, high = 0, 1
            style["color_mapper"] = LinearColorMapper(low=low, high=high)
```

```python
AttributeError [Call holoviews.ipython.show_traceback() for details]
unexpected attribute 'color_mapper' to ImageRGBA, possible attributes are anchor, decorations, dh, dh_units, dilate, dw, dw_units, global_alpha, image, js_event_callbacks, js_property_callbacks, name, origin, subscribed_events, syncable, tags, x or y
```

I also tried doing:
```python
        if self.clim_percentile:
            low, high = np.nanpercentile(img, (2, 98))
            img[img < low] = low
            img[img > high] = high

```

But it doesn't seem to work
<img width="401" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/db99629c-0844-4e80-99b9-c6b58cd03ab0">

**Comment by ahuang11** [comment]
Thoughts about having this in hvPlot?
https://github.com/holoviz/holoviews/pull/6137

I don't have a strong preference, but I do want to have a way forward.

**Comment by maximlt** [comment]
I also don't have strong preference :)

**Comment by philippjfr** [comment]
I'm -1 on adding this anywhere. Taking percentiles of RGB values just does not make sense to me.

**Comment by ahuang11** [comment]
If that's the case, how should users address this?

The initial goal was that I wanted to write a demo of how you can explore satellite imagery with hvplot easily, but then I encountered the issue that robust/clim_percentile was not exposed.

If robust/clim_percentile isn't implemented, its a tad tedious for the user to have to manually implement it for satellite imagery vs typing `robust=True`.

Would you prefer it be an operation? E.g. `Clip`?

**Comment by philippjfr** [comment]
Will have to look at it.

**Comment by philippjfr** [comment]
Yeah, looking at this dataset the values are not R G B values they are raw reflectance values for different spectra from a satellite. Visualizing them using an RGB element without first processing these values is simply incorrect. So the only thing I can imagine doing is providing some operation in geoviews.

**Comment by philippjfr** [comment]
https://ecampusontario.pressbooks.pub/remotesensing/chapter/chapter-5-visualization-and-manipulation-of-satellite-images/

**Comment by philippjfr** [comment]
Based on my reading of that the transformation is quite simple, you divide the red green blue values 2^8 and then cast to uint8.

**Comment by philippjfr** [comment]
Alternatively you can also apply histogram equalization.

**Comment by philippjfr** [comment]
Hmm, the division thing doesn't work.

eq_hist produces this:

![bokeh_plot - 2024-03-02T112323 123](https://github.com/holoviz/hvplot/assets/1550771/4e79f380-8aa7-4665-bb98-95afdb3070cf)

**Comment by philippjfr** [comment]
```
hv.RGB((da / (2**2)).clip(0, 255).astype(np.uint8).data.transpose([1, 2, 0])).opts(width=600)
```


![bokeh_plot - 2024-03-02T112755 242](https://github.com/holoviz/hvplot/assets/1550771/52551cb6-00a8-48d8-b0e6-f994426f89a6)

**Comment by philippjfr** [comment]
Okay, I've come around I'd be okay with a two-pronged approach, we implement the robust semantics in xarray and then HoloViews appropriately clips the data.

**Comment by ahuang11** [comment]
Philipp found the actual `_rescale_imshow_rgb` robust usage in xarray [here](https://github.com/pydata/xarray/blob/604bb6d08b942f774a3ba2a2900061959d2e091d/xarray/plot/utils.py#L729-L759)
