### ISSUE TITLE
Explorer: support exploring the variables of an xarray Dataset

### ISSUE THREAD

**Issue by maximlt** [holoviz/hvplot#1273]
Reviewing https://github.com/holoviz/hvplot/pull/1256 made me realize that the explorer doesn't support selecting the variables of an xarray Dataset, it seems to be picking up the first variable available (`air` in the example below).

```python
import hvplot.xarray
import xarray as xr

ds_at = xr.tutorial.open_dataset('air_temperature')
ds_at['air2'] = ds_at.air
ds_at.hvplot.explorer()
```

![image](https://github.com/holoviz/hvplot/assets/35924738/4ade98ba-5eb1-4e15-b3ab-8d3fba34d4b3)

**Comment by ahuang11** [comment]
Couldn't find the PR that fixed this:
<img width="1105" alt="image" src="https://github.com/holoviz/hvplot/assets/15331990/a60a1026-c6c9-4731-ab5d-a1572b90f1bd">
