### ISSUE TITLE
Alpha not supported with plotly backend

### ISSUE THREAD

**Issue by openSourcerer9000** [holoviz/hvplot#1290]
For a reproducible example,  look at your [own docs](https://hvplot.holoviz.org/user_guide/Plotting_with_Plotly.html):

![image](https://github.com/holoviz/hvplot/assets/61931826/489046a6-7215-48da-89b1-b7ffa445d6fb)

hvplot 0.8.1

**Comment by maximlt** [comment]
Definitely need to find a way to surface HoloViews issues that influence/were reported in hvPlot somewhere in hvPlot's GitHub tracker, as this issue has already been reported https://github.com/holoviz/holoviews/issues/5226.
