### ISSUE TITLE
No longer internally call `.reset_index()`

### ISSUE THREAD

**Issue by maximlt** [holoviz/hvplot#1292]
HoloViews is going to better support Pandas indexes in https://github.com/holoviz/holoviews/pull/6061 so it doesn't have to internally call `.reset_index()` when a reference is made to an index column. This change will come with some great performance improvements. hvPlot itself calls in several places `.reset_index()`. To fully benefit from HoloViews' improvements, hvPlot will have to remove these calls to `.reset_index()`.

**Comment by maximlt** [comment]
Bugs identified and fixed when working on addressing this:

- https://github.com/holoviz/hvplot/pull/1363
- https://github.com/holoviz/holoviews/pull/6299

**Comment by droumis** [comment]
Closed by #1350
