### ISSUE TITLE
xarray Dataset subplot variables

### ISSUE THREAD

**Issue by vadmbertr** [holoviz/hvplot#1294]
#### ALL software version info
Python 3.9.6
hvplot 0.9.2
xarray 2024.1.1
bokeh 3.3.4

#### Description of expected behavior and the observed behavior
Hi,

I'm trying to do a subplot of two variables of a xarray Dataset: `ds.hvplot(z=['temp', 'precip'], subplots=True)` but only one plot is displayed.
I think it is related to https://github.com/holoviz/hvplot/issues/336 (and https://stackoverflow.com/questions/58350586/generate-xarray-dataset-image-subplots).

#### Complete, minimal, self-contained example code that reproduces the issue

From the SO question:
```python
import xarray as xr
import numpy as np
import hvplot.xarray

ds = xr.Dataset({
    'temp': (('lon', 'lat'), 15 + 8 * np.random.randn(2, 2)),
    'precip': (('lon', 'lat'), 10 * np.random.rand(2, 2)),
    },
    coords={
        'lon': [-99.83, -99.32],
        'lat': [42.25, 42.21],
    })
ds.hvplot(z=['temp', 'precip'], subplots=True)
```

Thanks a lot for you work on the library!
Vadim

**Comment by Hoxbro** [comment]
This is because it is shown in a widgetbox:
![image](https://github.com/holoviz/hvplot/assets/19758978/74ec0288-9735-4320-a928-fd7d81c3c55b)

You can get them side-by-side with `ds.hvplot(z=['temp', 'precip'], subplots=True).layout()`

**Comment by vadmbertr** [comment]
Oh, I missed that indeed... It's working as expected, thanks a lot for the answer!
