### ISSUE TITLE
Issues with ImageStack support

### ISSUE THREAD

**Issue by maximlt** [holoviz/hvplot#1315]
Observed these issues while modernizing the Gerrymandering examples.

This is all with `rasterize=True` and working around a HoloViews bug (see https://github.com/holoviz/holoviews/issues/6187):

- When setting `aggregator=ds.count_cat('cat')`, plot options like `width` are not applied. The issue is there https://github.com/holoviz/hvplot/blob/ce7af4039f9de5c455fa5d517e0ef8759b59f3bb/hvplot/converter.py#L1432, the code sets the element type to be `Image` in that case and apply the options to the `Image` elements only, but there's none so they are dropped.
- I think I'd expect `rasterize=True, by='cat'` and `rasterize=True, aggregator=ds.count_cat('cat')` to create the same ImageStack plot.
- When setting `rasterize=True, by='cat'` the colorbar looks a little weird to me

```python
import datashader as ds
import numpy as np
import pandas as pd
import hvplot.pandas

num=10000

dists = {cat: pd.DataFrame(dict([('x',np.random.normal(x,s,num)), 
                                 ('y',np.random.normal(y,s,num)), 
                                 ('val',val), 
                                 ('cat',cat)]))      
         for x,  y,  s,  val, cat in 
         [(  2,  2, 0.03, 10, "d1"), 
          (  2, -2, 0.10, 20, "d2"), 
          ( -2, -2, 0.50, 30, "d3"), 
          ( -2,  2, 1.00, 40, "d4"), 
          (  0,  0, 3.00, 50, "d5")] }

df = pd.concat(dists,ignore_index=True)
df["cat"]=df["cat"].astype("category")

p = df.hvplot.scatter('x', 'y', rasterize=True, aggregator=ds.count_cat('cat'), width=800)
p
```

![image](https://github.com/holoviz/hvplot/assets/35924738/038b5b5c-0dd7-4a27-bd7c-954463b3dfa5)

```python
p2 = df.hvplot.scatter('x', 'y', rasterize=True, by='cat', width=800)
p2
```

![image](https://github.com/holoviz/hvplot/assets/35924738/037e0f56-81f0-4259-bef2-4d731a34e14d)

**Comment by Hoxbro** [comment]
> When setting rasterize=True, by='cat' the colorbar looks a little weird to me

This is the colorbar of an ImageStack.

**Comment by maximlt** [comment]
> > When setting rasterize=True, by='cat' the colorbar looks a little weird to me
> 
> This is the colorbar of an ImageStack.

Does the HoloViews doc explain how to understand this colorbar? My first impression was that it's a bug.

**Comment by Hoxbro** [comment]
Nope. I'm not a big fan of it either. But I don't think there is a nice way to represent multiple-dimensional colors in a single colorbar. Even if you have multiple colorbars, some colors could overlap on different, making it hard to see what bar a color belongs to. I see it as alpha values for the colors.

An explanation, if any, could be found in Bokeh. An example of it being used in pure Bokeh can be found here: https://github.com/bokeh/bokeh/pull/12356
