### ISSUE TITLE
Enable autorange for stacked area plots with positive and negative values

### ISSUE THREAD

**Issue by FabianHofmann** [holoviz/hvplot#1346]
Firstly, thank you for this great package!

I am regularly encountering an issue when wanting to create an area plot with positive and negative contributions and automatic axis scaling.

In particular, the functionality of `autorange='y'` fails when creating **two stacked area plots**, one with positive values and one with negative values only.  In this case, the auto-adjustment of the y-lims is either not active at all, or it only shows falls down to the positive or negative half of the plot.  

**Reproducible example**

```python
import pandas as pd
import numpy as np
import hvplot.pandas

# Generate example data
np.random.seed(0)
dates = pd.date_range('2021-01-01', periods=100)
data = pd.DataFrame({
    'date': dates,
    'A': np.random.rand(100).cumsum(),
    'B': np.random.rand(100).cumsum(),
    'C': -np.random.rand(100).cumsum()
}).set_index('date')

# Create individual stacked area plots for positive and neg. contributions to fix stacking, use autorange='y'
plot = data.clip(lower=0).hvplot(kind="area", stacked=True, autorange='y')
plot *= data.clip(upper=0).hvplot(kind="area", stacked=True, autorange='y')

# Display the plot
plot
```

I have tried various approaches to fix this issues, though without any luck. One particular approach was to try fixing the y-lim globally while leaving the x-axis zoomable. However, this does not seem to be supported either. 

Any help would be much appreciated.

**Comment by hoxbro** [comment]
Can you install the latest HoloViews version 1.18.3? 

I'm pretty sure we fixed it, though I can't remember when, so if that does not work, try installing the latest dev version (1.19.0a3) `pip install holoviews --pre`.

**Comment by maximlt** [comment]
I confirm this is fixed using the main branch of HoloViews. Closing the issue :)

**Comment by FabianHofmann** [comment]
@maximlt geeat to hear! Thank you very much!
