### ISSUE TITLE
Regression in stacked bar plots with x as datetime

### ISSUE THREAD

**Issue by jsignell** [holoviz/hvplot#1365]
#### ALL software version info
```
hvplot           : 0.10.0
holoviews        : 1.19.0
bokeh            : 3.4.2
python           : 3.12.4

# jupyter
IPython          : 8.26.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.3
jupyter_client   : 8.6.2
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 4.2.2
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.2.1
qtconsole        : not installed
traitlets        : 5.14.3
```
#### Description of expected behavior and the observed behavior

Stacked bar plot with `x` as datetime worked in previous versions of hvplot, but no longer seems to render properly:

![image](https://github.com/holoviz/hvplot/assets/4806877/67b19fd4-48aa-46b7-8cc2-fe6066f7515b)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import hvplot.pandas

plot_data = pd.read_csv("plot_data.csv", parse_dates=["t"])
plot_data.hvplot.bar(y="sec", x="t", by="func", stacked=True)
```
[plot_data.csv](https://github.com/user-attachments/files/16112214/plot_data.csv)

If you set `stacked=False`, the plot renders properly:
![image](https://github.com/holoviz/hvplot/assets/4806877/75a94460-9103-4b58-b619-d856b4eac933)

If you use a string column for `x`, the plot renders properly:

```python
plot_data.hvplot.bar(y="sec", x="month", by="func", stacked=True)
```
![image](https://github.com/holoviz/hvplot/assets/4806877/7d77af9f-03c0-4391-9b44-150b74c2725d)

**Comment by maximlt** [comment]
Guess it's a duplicate of https://github.com/holoviz/holoviews/issues/6288

**Comment by jsignell** [comment]
☝🏻 totally. I'll close this as a dupe.
