### ISSUE TITLE
Add a way remove the subplot label when combining plots under matplotlib backend

### ISSUE THREAD

**Issue by iuryt** [holoviz/hvplot#1370]
#### Is your feature request related to a problem? Please describe.
I am trying to combine plots, but I am not a big fan of the strong boldface subplot label that is added under matplotlib backend.

Example from documentation:
https://hvplot.holoviz.org/user_guide/Plotting_with_Matplotlib.html
```python
(crime.hvplot.bar(x='Year', y='Violent Crime rate', rot=90, width=550) +
 crime.hvplot.table(['Year', 'Population', 'Violent Crime rate'], width=420))
```
![image](https://github.com/user-attachments/assets/1ed005d3-67e9-48fe-af12-b7c349f6a5cc)

#### Describe the solution you'd like

I think that the subplot label should be off by default, and maybe we could set true or change the format.
I believe this is really useful, but if we had a way to change the style.
Not sure I am asking for something that is already there. I couldn't find a way to change it.

#### Describe alternatives you've considered

Just plotting with matplotlib.

**Comment by ahuang11** [comment]
Since hvPlot is based off HoloViews, you can do so through `.opts()`

```python
(hv.Curve([]) + hv.Curve([])).opts(sublabel_size=0)
```

There might be a better way to do this though so check `hv.help(hv.Layout)`

**Comment by iuryt** [comment]
> ```python
> .opts(sublabel_size=0)
> ```

I can work on the docs.

**Comment by iuryt** [comment]
> hv.help(hv.Layout)

This is tricky.

`.opts(sublabel_size=0)` kind of works, but there is still a pixel there.

![image](https://github.com/user-attachments/assets/3e00956e-0909-450c-a7e6-bec8fb51caef)


Even if I do something like:
```python
(
    crime.hvplot.bar(x='Year', y='Violent Crime rate', rot=90, width=550)+
    crime.hvplot.table(['Year', 'Population', 'Violent Crime rate'], width=420)
).opts(sublabel_size=0, hspace=0, sublabel_position=(0.5,0.5))
```

![image](https://github.com/user-attachments/assets/81e6993a-cbde-4789-9183-5c706020ec99)


The only options that are related to `sublabel`

![image](https://github.com/user-attachments/assets/b62ee03e-5ebc-43b4-804c-2e99a42862ff)

I tried to put `None` or `(None, None)` to all of them and doesn't seem to work.
Maybe we need to implement something here?

https://github.com/holoviz/holoviews/blob/55856e1b17850129144b9dd0d27fcc2b770c76a3/holoviews/plotting/mpl/plot.py#L209-L232

**Comment by ahuang11** [comment]
`sublabel_format` alpha?

            if '{Alpha}' in self.sublabel_format:
                labels['Alpha'] = int_to_alpha(layout_num-1)

**Comment by ahuang11** [comment]
Maybe sublabel_position to an extreme number to push it off the page.

**Comment by iuryt** [comment]
The `alpha` is actually for alphabet, I think. haha
This is why it is usually better to use the full word, whenever possible.

**Comment by iuryt** [comment]
`sublabel_format=""` does the job and doesn't seem as weird as doing `sublabel_size=0`. Thanks!
I will add to the docs.

**Comment by iuryt** [comment]
@ahuang11 
Few questions.
In terms of docs improvement, there are two ways and they are not mutually exclusive.

# Option 1:
I could create an extra example to the plot on
https://hvplot.holoviz.org/user_guide/Plotting_with_Matplotlib.html

For example, we could mention about customization after showing this plot
![image](https://github.com/user-attachments/assets/b9ca8f62-2060-46be-ade7-6e1a21ddffc9)

Something like making the same plot with `a)` and `b)` instead of boldface `A` and `B`, select some xticks for plot A to reduce the clutter and mention that if the user doesn't want the subplot labels can set `sublabel_format=""`.

# Option 2:

Examples from 
https://hvplot.holoviz.org/user_guide/Customization.html
are just for line plots and that't why it doesn't have `sublabel_*` options or it is just outdated?

**Comment by ahuang11** [comment]
I like Option 1, and in Option 2 customization page, I'd like to see a mention of using HoloViews .opts and link to HoloViews customization page.

**Comment by ahuang11** [comment]
On a second thought, maybe you can contribute an `opt` in HoloViews to disable the sublabels. Let me know if you're interested.

**Comment by philippjfr** [comment]
There is an option to remove sublabels, although it is unintuitive. At this point I'd be in favor of disabling the labels by default in HoloViews, you can do that globally now with:

```python
from holoviews.core.options import Options

options = hv.Store.options(backend='matplotlib')
options.Layout = Options('plot', sublabel_format=None)
```
