### ISSUE TITLE
Automatically or manually toggle to automatically use lon_lat_to_easting_northing

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#1375]
Sometimes, I don't want to use geoviews because it's extra dependency and import (and sometimes [it breaks](https://github.com/holoviz/hvplot/issues/1374)):

```python
import hvplot.xarray
import xarray as xr
import holoviews as hv
from holoviews.util.transform import lon_lat_to_easting_northing

ds = xr.tutorial.load_dataset("air_temperature").isel(time=slice(0, 100))
ds["easting"], ds["northing"] = lon_lat_to_easting_northing(ds["lon"], ds["lat"])
ds = ds.swap_dims({"lon": "easting", "lat": "northing"})
hv.element.tiles.CartoDark() * ds.hvplot("easting", "northing")
```
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/18b53a35-6a59-47f5-9ef0-74cc7872d3d4">

I'm wondering whether there should be a kwarg to transform so the above can be simplified down to

```python
import hvplot.xarray
import xarray as xr

ds = xr.tutorial.load_dataset("air_temperature").isel(time=slice(0, 100))
ds.hvplot("lon", "lat", tiles=True, to_easting_northing=True)  # or some other kwarg
```

Or, if it detects the x is between -180, 360 and y is between -90, 90 without any crs/projection kwargs, automatically convert to easting/northing?

```python
import hvplot.xarray
import xarray as xr

ds = xr.tutorial.load_dataset("air_temperature").isel(time=slice(0, 100))
# automatic detection
ds.hvplot("lon", "lat", tiles=True)
```

**Comment by jbednar** [comment]
I'd be ok with assuming lat,lon inputs with `geo=True` and projecting them using our own internal functions from HoloViews without having to bring in geoviews/cartopy/proj for that one common case. I would not be ok with checking the ranges and automatically converting; at best that could be a warning (maybe people really _do_ want to look at some tiny area of the earth, or vice versa!).

**Comment by ahuang11** [comment]
Okay I think a warning is probably good, because without it, the data is centered around 0 and that can be confusing.

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/36428535-5731-424b-88ea-d2ad7eb1b320">
