### ISSUE TITLE
hvplot stacked bars dont work

### ISSUE THREAD

**Issue by benbarn313** [holoviz/hvplot#1386]
When running an example from the hvplot docs, plot items do not render.

I noticed this was an issue after attempting to create a stacked histogram with a different dataset.
I attempted the example on the site and got similar results.

```
import hvplot.pandas
from hvplot.sample_data import us_crime

crime = us_crime.read()

crime.hvplot.bar(x='Year', y=['Violent crime total', 'Property crime total'],
                 stacked=True, rot=90, width=800, legend='top_left')
```

![image](https://github.com/user-attachments/assets/e29a96da-76e4-404b-abd7-fb8d5251b900)

holoviews   1.19.1
hvplot   0.10.0
pandas   2.1.4

**Comment by hoxbro** [comment]
I think this is a duplicate of https://github.com/holoviz/holoviews/issues/6288

**Comment by benbarn313** [comment]
@hoxbro It pretty much is, except the x axis here isnt continuous.

Casting the years to strings seems to fix it as mentioned in https://github.com/holoviz/hvplot/issues/1365

```
import hvplot.pandas
from hvplot.sample_data import us_crime

crime = us_crime.read().astype({'Year': 'str'})


crime.hvplot.bar(x='Year', y=['Violent crime total', 'Property crime total'],
                 stacked=True, rot=90, width=800, legend='top_left')
```

![image](https://github.com/user-attachments/assets/a6c813cf-b361-40a0-9ffb-48ea8801e6db)

going to mark as closed
