### ISSUE TITLE
hvplot Explorer is giving nuisance Line plot when using over 10,000 points

### ISSUE THREAD

**Issue by hagaishalevaei** [holoviz/hvplot#1406]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
Windows 11, 
Python=3.11.9,
 Jupyterlab  4.2.5, 
hvplot 0.10.0 
pandas 2.2.2 

#### Description of expected behavior and the observed behavior
Using Python hvplot Explorer is giving nuisance Line plot when using over 10,000 points. Is that a bug? can I configure the threshold value?

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
import hvplot.pandas

N=1001
Range = 10
DF = []
for n in range(Range):
    x = np.linspace(0.0, 6.4, num=N)
    y = np.sin(x) + n/10
    df = pd.DataFrame({'x': x, 'y': y})
    df['#'] = n 
    DF.append(df)

DF = pd.concat(DF)
print(f'param number= {N*Range}')
DF.hvplot.explorer(x='x', y='y', by = ['#'], kind='line')
```

```
```

#### Stack traceback and/or browser JavaScript console output
https://stackoverflow.com/questions/78950183/python-hvplot-explorer-limit-of-10-000-point

#### Screenshots or screencasts of the bug in action
![image](https://github.com/user-attachments/assets/4c2cae79-ef01-4b95-b27b-995067dfbd3c)

![image](https://github.com/user-attachments/assets/e52166c1-2727-4fbf-9acd-b2799e63f50c)

- [ ] I may be interested in making a pull request to address this

**Comment by hagaishalevaei** [comment]
Digging in the hvplot code I found in \site-packages\hvplot\ui.py MAX_ROWS = 10000. Changing to MAX_ROWS = 100001 solved the issue.

**Comment by ahuang11** [comment]
To clarify, nuisance in this sense means that it's not showing over 10k lines?

I suppose to improve this, we can add a editable slider widget to max out number of lines.

**Comment by hagaishalevaei** [comment]
@ahuang11 - it is not 10k lines. The lines starting to act strange when the total amount of points is over 10,000. for example if you got 10 lines of 999 points there will be no problem, but if each line will be 1001 points you will get this strange thing.   


Good
```
N=999
Range = 10
DF = []
for n in range(Range):
    x = np.linspace(0.0, 6.4, num=N)
    y = np.sin(x) + n/10
    df = pd.DataFrame({'x': x, 'y': y})
    df['#'] = n 
    DF.append(df)

DF = pd.concat(DF)
print(f'param number= {N*Range}')
DF.hvplot.explorer(x='x', y='y', by = ['#'], kind='line')
```
Bad

```
N=1001
Range = 10
DF = []
for n in range(Range):
    x = np.linspace(0.0, 6.4, num=N)
    y = np.sin(x) + n/10
    df = pd.DataFrame({'x': x, 'y': y})
    df['#'] = n 
    DF.append(df)

DF = pd.concat(DF)
print(f'param number= {N*Range}')
DF.hvplot.explorer(x='x', y='y', by = ['#'], kind='line')
```

**Comment by ahuang11** [comment]
Okay here's the logic. I don't think it's supposed to sample if it's a line plot.
```
        if len(df) > MAX_ROWS and not (
            self.kind in KINDS['stats'] or kwargs.get('rasterize') or kwargs.get('datashade')
        ):
            df = df.sample(n=MAX_ROWS)
```

**Comment by hagaishalevaei** [comment]
@ahuang11 - I don't know what is the cost for such a change, but using `df = df.sample(n=MAX_ROWS).sort_index()` will solve the issue. 
Apparently pandas.DataFrame.sample returns random order 
https://stackoverflow.com/questions/59594516/how-to-sample-from-pandas-dataframe-while-keeping-row-order

![image](https://github.com/user-attachments/assets/f428dc7e-8818-4333-850e-7c42149a16cc)

**Comment by ahuang11** [comment]
In the PR, I just used .head()

**Comment by hagaishalevaei** [comment]
My opinion is that `sample().sort_index()` is better than `head()` in most cases. 
![image](https://github.com/user-attachments/assets/465af366-043e-43e9-aec6-658bf19bb0c7)

**Comment by maximlt** [comment]
@hagaishalevaei feel free to directly review https://github.com/holoviz/hvplot/pull/1408 :)
