### ISSUE TITLE
Tooltip not working on the reference gallery (Area Chart)

### ISSUE THREAD

**Issue by sorukumar** [holoviz/hvplot#1407]
I see that tooltip has missing values in the reference example for area chart. 

example: 
https://hvplot.holoviz.org/reference/tabular/area.html
![Screen Shot 2024-09-06 at 10 10 27 AM](https://github.com/user-attachments/assets/cb2330ba-a04d-41e4-b8fc-d0a914ed43da)

**Comment by ahuang11** [comment]
Thanks for the report. It's an upstream issue so I'll be closing this. https://github.com/holoviz/holoviews/issues/5375
