### ISSUE TITLE
No tooltips for subcoordinate ridge plots

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#1427]
The ridge plots in the hvPlot 0.11 release blog post have invalid tooltips

https://blog.holoviz.org/posts/hvplot_release_0.11/

![image](https://github.com/user-attachments/assets/8d75e406-7a7b-4dcf-b751-6178d105c4c7)

My request is to add valid tooltips. But if that is difficult and removing them is easy, then that could be a first step. Tooltips with `???` is a worse user experience than no tooltips.

**Comment by maximlt** [comment]
Duplicate of https://github.com/holoviz/holoviews/issues/5375. I'm going to update the blog post to hide the tooltips. Thanks for raising that.
