### ISSUE TITLE
Stacked bar plot is broken in hvplot 0.11.0

### ISSUE THREAD

**Issue by mosc9575** [holoviz/hvplot#1429]
In the latest version of `hvplot` plotting stacked bars from a DataFrame with multiple columns is broken.

See the [second example](https://hvplot.holoviz.org/user_guide/Plotting.html#bars) in the latest docs.

#### minimal example

```python
from hvplot.sample_data import us_crime

crime = us_crime.read()
print(type(crime))
crime.head()

crime.hvplot.bar(x='Year', y=['Violent crime total', 'Property crime total'],
                 stacked=True, rot=90, width=800, legend='top_left')
```

![grafik](https://github.com/user-attachments/assets/02b9e152-27d8-4753-9222-82d8936f55c5)

I `y` is a string and not a list, the bar plot works!

**Comment by hoxbro** [comment]
I should have fixed this in HoloViews with https://github.com/holoviz/holoviews/pull/6365, but it has yet to be released.

**Comment by maximlt** [comment]
Fixed on the website by building it with a dev release of HoloViews. The underlying issue will be fixed when HoloViews 1.20 is released.

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/2e62f2da-d844-430d-91f5-133853279f0e">

**Comment by davidleitch1** [comment]
Just want to note the same problem. Could have saved myself a few hours of work by looking here earlier. cheers

**Comment by hadleyrich** [comment]
Is there a dev version published that has this fix?

**Comment by maximlt** [comment]
Yes, you need to install the latest dev version of holoviews.

**Comment by hadleyrich** [comment]
> Yes, you need to install the latest dev version of holoviews.

Thanks @maximlt for answering. I had missed the fact that it was holoviews upstream and not hvplot so was confused when looking for a dev release and not finding anything above 0.11.0. From your pointer I've now added holoviews@v1.20.0rc0 and it is working as expected.
