### ISSUE TITLE
NetworkX Hover Tooltips Not Working Since 0.11.0

### ISSUE THREAD

**Issue by Palmr** [holoviz/hvplot#1437]
#### ALL software version info

<details>
    <summary>Software Version Info</summary>

```plaintext
hvplot=0.11.0

Python 3.10.14
Jupyter Lab 4.2.5
```
</details>

#### Description of expected behavior and the observed behavior

I expected the hover tool to show node (or edge if `inspection_policy='edges'`) attributes.

Instead it shows the list of attributes by name, but the value is always the string `@{{dimension_sanitizer(name)}}`

This can be seen on the hvplot NetworkX page when hovering a node on any graphs: https://hvplot.holoviz.org/user_guide/NetworkX.html

I'm fairly sure this is down to this 
https://github.com/holoviz/hvplot/commit/a56c997bc5b0ee8ab37460927b9f57311c56bfe0#diff-7b2c154f4174f90a12e76d0fdb8fe4cf66c4fe743844fe9b7050a568bc501f8eL335

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import hvplot.networkx as hvnx
import networkx as nx

hvnx.draw(nx.petersen_graph())
```

**Comment by hoxbro** [comment]
I think it is related to this PR: https://github.com/holoviz/holoviews/pull/6180

**Comment by Palmr** [comment]
> Are you up for submitting a PR to fix it?

I've given it a go :crossed_fingers:
