### ISSUE TITLE
Bar chart not displaying correctly

### ISSUE THREAD

**Issue by nconsulting** [holoviz/hvplot#1450]
#### ALL software version info
<details>
    <summary>Software Version Info</summary>

```plaintext
hvplot=0.11.1
holoviews=1.20.0rc0 (same problem with 0.11.1, I upgraded to the rc to see if it fixes the problem, which it doesn't)
python= 3.10.10
polars=1.12.0
bokeh=3.6.0
```
</details>

#### Description of expected behavior and the observed behavior
Bars are to wide and overlap each other. In previous versions bars were small and each ratio had its one distinguisable bar.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
hv.extension("bokeh")
import hvplot.polars
import polars as pl

dic = {"ratio": [0.82, 1.11, 1.18, 1.2, 1.21, 1.23, 1.24, 1.25, 1.28, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4, 1.41, 1.42, 1.43, 1.44, 1.45],
       "count": [1, 2, 1, 3, 1, 1, 2, 7, 2, 4, 1, 2, 2, 3, 2, 1, 17, 35, 73, 173, 6606, 63550]}

pl_df = pl.DataFrame(dic)

print(pl_df)
pl_df.hvplot.bar(x="ratio", y="count", grid=True, height=600, rot=90, shared_axes=False, width=1345)

```

#### Screenshots or screencasts of the bug in action
Screenshot is from the chart generated with actual data. The code example is a simplified version with less data.
![bar_chart](https://github.com/user-attachments/assets/f2575164-8229-4275-b672-b849507e1a74)

**Comment by maximlt** [comment]
@nconsulting this is fixed in HoloViews and is going to be released in version 1.20.0.

> In previous versions bars were small and each ratio had its one distinguisable bar.

Something else that changed compared to previous versions is that HoloViews since version 1.19.0 allows Bar plots to be plotted on continuous axes and not just categorical. Before that and adapted to your example, the `ratio` data was considered categorical, even if it's numeric data. If for some reason that's the behavior you need, you can always cast `ratio` to string before plotting.

**Comment by nconsulting** [comment]
@maximlt Thank you very much for the quick fix. I'll keep your message in mind, once I get my hands on the fixex HoloViews. Any idea when 1.20.0 will be available or an rc version with the fix?

**Comment by maximlt** [comment]
> [@maximlt](https://github.com/maximlt) Thank you very much for the quick fix. I'll keep your message in mind, once I get my hands on the fixex HoloViews. Any idea when 1.20.0 will be available or an rc version with the fix?

1.20.0rc1 has been released with this fix.
