### ISSUE TITLE
[Question]How can I not show the dates with no data in the OHLC chart?

### ISSUE THREAD

**Issue by Gwill** [holoviz/hvplot#1460]
How can I not show the dates with no data in the OHLC chart so that the graph is continuous?

In example: https://hvplot.holoviz.org/reference/tabular/ohlc.html

how to not show the non trading dates' data with empty in chat?

**Comment by vanheck** [comment]
Do you mean skip the gaps? https://github.com/holoviz/hvplot/issues/1458
