### ISSUE TITLE
save as file

### ISSUE THREAD

**Issue by fipoucat** [holoviz/hvplot#1464]
Maybe a simple question?
I am producing plots using hvplot and wonder how to save them as files in png, tiff or pdf.

Thak you.

**Comment by maximlt** [comment]
Hi @fipoucat, user questions are best suited for the [HoloViz Forum](https://discourse.holoviz.org/c/hvplot/8) or [Discord](https://discord.gg/AXRHnJU6sP).

You'll find some answers on these pages:
- https://hvplot.holoviz.org/user_guide/Viewing.html
- https://holoviews.org/user_guide/Exporting_and_Archiving.html
- https://holoviews.org/user_guide/Plotting_with_Bokeh.html
- https://holoviews.org/user_guide/Plotting_with_Matplotlib.html
