### ISSUE TITLE
How to display index with table plot.

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/hvplot#151]
The table rendered from hvplot.streamz does not display the index values. Is there a way to do this?

**Comment by philippjfr** [comment]
For now you use reset_index to add the index to the regular columns.

**Comment by philippjfr** [comment]
The question is whether we want to do this by default.

**Comment by maximlt** [comment]
It seems to me that it does display the index.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/35924738/195054841-4833f595-79d4-445c-8cc7-5a637ede7c73.png">

I'm closing this issue then, don't hesitate to comment it or open a new issue if you think the problem isn't gone.
