### ISSUE TITLE
Plotting API defaults should be over-ridden with user defined kwargs (intake)

### ISSUE THREAD

**Issue by jsignell** [holoviz/hvplot#181]
<img width="1018" alt="screen shot 2018-09-28 at 3 43 32 pm" src="https://user-images.githubusercontent.com/4806877/46230071-6a5d9100-c335-11e8-874b-923610c768c2.png">

From https://github.com/intake/intake/issues/171

**Comment by philippjfr** [comment]
Seems like a straightforward fix. We just need to check if the explicit x/y are passed in they are correctly merged with the definition in the catalogue.

**Comment by philippjfr** [comment]
This has been fixed for a while. Can't find the exact commit now.
