### ISSUE TITLE
hexbin ignores padding argument

### ISSUE THREAD

**Issue by ivirshup** [holoviz/hvplot#182]
Currently, hexbin silently ignores the `padding` argument. It would be useful if this worked, since by default bins can be out of frame. Here's a little example:

```python
import pandas as pd
import numpy as np
import hvplot.pandas

df = pd.DataFrame(np.random.randn(10000, 2), columns=["x", "y"])
(df.hvplot.hexbin("x", "y") + df.hvplot.hexbin("x", "y", padding=(5, 100))).cols(1)
```

<img width="895" alt="image" src="https://user-images.githubusercontent.com/8238804/53854222-b3202100-401c-11e9-90e7-f7fe0a62f4a6.png">

**Comment by philippjfr** [comment]
Appears to be fixed with latest HoloViews.
