### ISSUE TITLE
[API] port nxviz API to hvplot

### ISSUE THREAD

**Issue by ericmjl** [holoviz/hvplot#209]
I'd like to solicit some help with porting the nxviz API to hvplot.

nxviz's goal is to provide a declarative API for rational graph viz, so we move away from hairballs and move towards beautiful viz that, hopefully, can also be interactive!

@philippjfr will you be at SciPy 2019? If so, would you have time to chat over this issue?

**Comment by jbednar** [comment]
Philipp won't, but I'll be there with @jsignell and @jlstevens , and we'd be happy to brainstorm about this!

**Comment by philippjfr** [comment]
I'd love to see this. I wasn't very happy porting the networkx plotting API but wasn't aware that nxviz existed. Would also be happy to chat about this via video chat. I'll read through the nxviz code tomorrow to see how hard the port would be.

**Comment by maximlt** [comment]
Closing in favor of https://github.com/holoviz/hvplot/issues/487
