### ISSUE TITLE
scatter 3d

### ISSUE THREAD

**Issue by joshua-gould** [holoviz/hvplot#225]
It would be nice to add support for 3d scatter plots (http://holoviews.org/reference/elements/matplotlib/Scatter3D.html)

**Comment by jsignell** [comment]
Right that is currently not supported in bokeh, which is the only backend that is set up so far in hvplot. See #56

**Comment by philippjfr** [comment]
This is tied up with https://github.com/holoviz/hvplot/issues/480 so I'll close.
