### ISSUE TITLE
Using hvplot inside a docker container

### ISSUE THREAD

**Issue by kyochujoho** [holoviz/hvplot#300]
Hi, I would like to view the output of hvplot.show() while running it inside of a docker container. Having a new html file open up on the local host for every image generated (default behavior) would be preferred, but using a specific port every time would be fine too (for port-forwarding). Is there a straightforward manner for configuring this?

**Comment by jsignell** [comment]
We will add a port argument

**Comment by philippjfr** [comment]
.show now just mirrors the panel show method which supports a port argument.
