### ISSUE TITLE
Using a continuous colormap for categorical data.

### ISSUE THREAD

**Issue by jsignell** [holoviz/hvplot#327]
When a continuous colormap is used for categorical data, the values should be chosen to span the colormap, rather than the first n being chosen. Here is how it works in matplotlib for instance:

```python
import numpy as np
import pandas as pd

%matplotlib inline

cmap = 'cubehelix'

df = pd.DataFrame(np.random.randn(1000, 10), index=pd.date_range('1/1/2000', periods=1000))
df = df.cumsum()
df.plot(colormap=cmap)
```
<img width="392" alt="Screen Shot 2019-10-08 at 11 15 17 AM" src="https://user-images.githubusercontent.com/4806877/66408441-f5e41600-e9bc-11e9-9e56-5f3a7deb53a2.png">

```python
pd.options.plotting.backend = 'holoviews'
df.plot(colormap=cmap)
```
<img width="725" alt="Screen Shot 2019-10-08 at 11 15 23 AM" src="https://user-images.githubusercontent.com/4806877/66408454-f8df0680-e9bc-11e9-9fd2-c77f46a7b14b.png">

## Workaround

```python
from holoviews.plotting.util import process_cmap
cmap = process_cmap('cubehelix', ncolors=10, categorical=True)

df.plot(colormap=cmap)
```

<img width="731" alt="Screen Shot 2019-10-08 at 11 18 37 AM" src="https://user-images.githubusercontent.com/4806877/66408692-67bc5f80-e9bd-11e9-85e9-9300e3b30010.png">

**Comment by DanielRudnicki** [comment]
Is there any workaround for hvplot() using geo=True option?

**Comment by philippjfr** [comment]
@DanielRudnicki I suggest filing a question (with a reproducible example) on our [Discourse](https://discourse.holoviz.org/) site.
