### ISSUE TITLE
`shared_axes` isn't working as expected

### ISSUE THREAD

**Issue by jsignell** [holoviz/hvplot#328]
When running through the docs I ran into this on the Subplots notebooks. It looks like `axiswise` is getting set correctly, so this might be a holoviews bug. 

```python
import hvplot.pandas
from hvplot.sample_data import airline_flights, us_crime

us_crime.hvplot(x='Year', y=['Robbery',  'Robbery rate', 'Burglary', 'Burglary rate'], 
                width=350, height=300, subplots=True, shared_axes=False).cols(2)
```

**Comment by SandervandenOord** [comment]
Is there a workaround for getting different y-ranges with hvplot when using subplots=True?
I had the same problem as above using shared_axes=False, so I now end up with the y-range for all my graphs which I really don't want:

```
import numpy as np
import pandas as pd
import hvplot
import hvplot.pandas

col1 = np.random.normal(loc=0.0, size=[14, ])
col2 = np.random.normal(loc=300.0, size=[14, ])

df = pd.DataFrame(
    data = {
        'col1': col1, 
        'col2': col2
    })

df.hvplot.scatter(x='index', y=['col1', 'col2'], subplots=True, shared_axes=False).cols(1)
```

**Comment by SandervandenOord** [comment]
This bug came with the new Holoviews 1.12.6.
With Holoviews 1.12.5 there is no problem.
Hvplot 0.5.2.

**Comment by SandervandenOord** [comment]
This is working as expected again.

I just tested my code example above with:
holoviews==1.13.0a17.post12+g89bfcfbe
hvplot==0.5.2.post12+g1c76c1f

So I think this issue can be closed.
