### ISSUE TITLE
Datetime plotting functionality issue

### ISSUE THREAD

**Issue by TylerTCF** [holoviz/hvplot#348]
When making a dataframe with a datetime64 and plotting a float or int, I have no problems using hvplot.  See example here:

```
import pandas as pd
import numpy as np
import holoviews as hv
import hvplot.pandas

df2=pd.DataFrame({'Col1' : ['8/17/1981', '9/17/1981', '10/17/1981', '11/17/1981', '12/17/1981'], 'Col2' : [30, 99, 45, 5, 3], 'Col3' : [11, 12, 13, 5, 6]})
df2.Col1=pd.to_datetime(df2.Col1)
df2=df2.resample('M', on='Col1').sum()
df2.reset_index(inplace=True)
df2.Col2=df2.Col2.astype(float)
df2.Col3=df2.Col3.astype(float)
print(df2.dtypes)
df2.hvplot('Col1', 'Col2')

```
This code produces a plot as expected.

**However, when I have a user who reindexes the dataframe (see code below) it produces an error in plotting.  Both dataframes show dtypes of datetime64, float, and float.  I don't see why it should error.**

```
sample='M'
all_days = pd.date_range('1/1/1900', '1/1/2020', freq=sample)
df2=pd.DataFrame({'Col1' : ['8/17/1981', '9/17/1981', '10/17/1981', '11/17/1981', '12/17/1981'], 'Col2' : [30, 99, 45, 5, 3], 'Col3' : [11, 12, 13, 5, 6]})
df2.Col1=pd.to_datetime(df2.Col1)
df2=df2.resample('M', on='Col1').sum().reindex(all_days).fillna(0)
df2.reset_index(inplace=True)
df2.rename(columns={'index':'Col1'}, inplace=True)
df2.Col2=df2.Col2.astype(float)
df2.Col3=df2.Col3.astype(float)
print(df2.dtypes)
df2.hvplot('Col1', 'Col2')
```

**This works on the reindexed datetime code above:**
`hv.Curve(df2, ['Col1', 'Col2'])`

The following is the error output:
`OSError                                   Traceback (most recent call last)
~\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~\Anaconda3\lib\site-packages\holoviews\core\dimension.py in _repr_mimebundle_(self, include, exclude)
   1291         hooks.  The output of all registered display_hooks is then
   1292         combined and returned.
-> 1293         """
   1294         return Store.render(self)
   1295 

~\Anaconda3\lib\site-packages\holoviews\core\options.py in render(cls, obj)
   1360         for _, type_hooks in cls._display_hooks.items():
   1361             for cls in class_hierarchy:
-> 1362                 if cls in type_hooks:
   1363                     hooks.append(type_hooks[cls])
   1364                     break

~\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in pprint_display(obj)
    278     ip = get_ipython()  #  # noqa (in IPython namespace)
    279     if not ip.display_formatter.formatters['text/plain'].pprint:
--> 280         return None
    281     return display(obj, raw_output=True)
    282 

~\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in display(obj, raw_output, **kwargs)
    248             output = grid_display(obj)
    249     elif isinstance(obj, (CompositeOverlay, ViewableElement)):
--> 250         with option_state(obj):
    251             output = element_display(obj)
    252     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):

~\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in wrapped(element)
    143 
    144         try:
--> 145             max_frames = OutputSettings.options['max_frames']
    146             mimebundle = fn(element, max_frames=max_frames)
    147             if mimebundle is None:

~\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in element_display(element, max_frames)
    189     if type(element) not in Store.registry[backend]:
    190         return None
--> 191 
    192     return render(element)
    193 

~\Anaconda3\lib\site-packages\holoviews\ipython\display_hooks.py in render(obj, **kwargs)
     66         renderer = renderer.instance(fig='png')
     67 
---> 68     return renderer.components(obj, **kwargs)
     69 
     70 

~\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\renderer.py in components(self, obj, fmt, comm, **kwargs)
    248         # Bokeh has to handle comms directly in <0.12.15
    249         comm = False if bokeh_version < '0.12.15' else comm
--> 250         return super(BokehRenderer, self).components(obj,fmt, comm, **kwargs)
    251 
    252 

~\Anaconda3\lib\site-packages\holoviews\plotting\renderer.py in components(self, obj, fmt, comm, **kwargs)
    319             plot = obj
    320         else:
--> 321             plot, fmt = self._validate(obj, fmt)
    322 
    323         data, metadata = {}, {}

~\Anaconda3\lib\site-packages\holoviews\plotting\renderer.py in _validate(self, obj, fmt, **kwargs)
    218         if isinstance(obj, tuple(self.widgets.values())):
    219             return obj, 'html'
--> 220         plot = self.get_plot(obj, renderer=self, **kwargs)
    221 
    222         fig_formats = self.mode_formats['fig'][self.mode]

~\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\renderer.py in get_plot(self_or_cls, obj, doc, renderer, **kwargs)
    133             curdoc().theme = self_or_cls.theme
    134         doc.theme = self_or_cls.theme
--> 135         plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
    136         plot.document = doc
    137         return plot

~\Anaconda3\lib\site-packages\holoviews\plotting\renderer.py in get_plot(self_or_cls, obj, renderer, **kwargs)
    205             init_key = tuple(v if d is None else d for v, d in
    206                              zip(plot.keys[0], defaults))
--> 207             plot.update(init_key)
    208         else:
    209             plot = obj

~\Anaconda3\lib\site-packages\holoviews\plotting\plot.py in update(self, key)
    593         before finally looking up the default projection on
    594         the plot type. If more than one non-None projection
--> 595         type is found an exception is raised.
    596         """
    597         isoverlay = lambda x: isinstance(x, CompositeOverlay)

~\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\element.py in initialize_plot(self, ranges, plot, plots, source)
   1257         if self.batched:
   1258             element = [el for el in self.hmap.data.values() if el][-1]
-> 1259         else:
   1260             element = self.hmap.last
   1261         key = util.wrap_tuple(self.hmap.last_key)

~\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\element.py in _init_glyphs(self, plot, element, ranges, source)
   1204         hover.renderers.append(renderer)
   1205 
-> 1206         # If datetime column is in the data replace hover formatter
   1207         for k, v in source.data.items():
   1208             if k+'_dt_strings' in source.data:

~\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\chart.py in get_data(self, element, ranges, style)
    340         if 'steps' in self.interpolation:
    341             element = interpolate_curve(element, interpolation=self.interpolation)
--> 342         data = {x: element.dimension_values(xidx),
    343                 y: element.dimension_values(yidx)}
    344         self._get_hover_data(data, element)

~\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\element.py in _get_hover_data(self, data, element, dimensions)
    280                 data[dim] = element.dimension_values(d)
    281             values = np.asarray(data[dim])
--> 282             if (values.dtype.kind == 'M' or (
    283                     len(values) and isinstance(values[0], util.datetime_types))):
    284                 data[dim+'_dt_strings'] = [d.pprint_value(v) for v in values]

~\Anaconda3\lib\site-packages\holoviews\plotting\bokeh\element.py in <listcomp>(.0)
    280                 data[dim] = element.dimension_values(d)
    281             values = np.asarray(data[dim])
--> 282             if (values.dtype.kind == 'M' or (
    283                     len(values) and isinstance(values[0], util.datetime_types))):
    284                 data[dim+'_dt_strings'] = [d.pprint_value(v) for v in values]

~\Anaconda3\lib\site-packages\holoviews\core\dimension.py in pprint_value(self, value)
    415                 if isinstance(value, (dt.datetime, dt.date)):
    416                     return value.strftime(formatter)
--> 417                 elif isinstance(value, np.datetime64):
    418                     return util.dt64_to_dt(value).strftime(formatter)
    419                 elif re.findall(r"\{(\w+)\}", formatter):

~\Anaconda3\lib\site-packages\holoviews\core\util.py in dt64_to_dt(dt64)
   1837         index -= indexes[-1] * p
   1838     indexes.append(index)
-> 1839     return tuple(v[i] for v, i in zip(values, indexes))
   1840 
   1841 

OSError: [Errno 22] Invalid argument

:Curve   [Col1]   (Col2)`

My pip list:
Package                            Version    
---------------------------------- -----------
-umpy                              1.16.2     
absl-py                            0.8.1      
alabaster                          0.7.12     
anaconda-client                    1.7.2      
anaconda-navigator                 1.9.6      
anaconda-project                   0.8.2      
antlr4-python3-runtime             4.7.2      
appdirs                            1.4.3      
asn1crypto                         0.24.0     
astor                              0.8.0      
astroid                            2.2.5      
astropy                            3.1.2      
atomicwrites                       1.3.0      
attrs                              19.1.0     
Babel                              2.6.0      
backcall                           0.1.0      
backports.os                       0.1.1      
backports.shutil-get-terminal-size 1.0.0      
beautifulsoup4                     4.7.1      
bitarray                           0.8.3      
bkcharts                           0.2        
bleach                             3.1.0      
bokeh                              1.3.4      
boto                               2.49.0     
boto3                              1.9.250    
botocore                           1.12.250   
Bottleneck                         1.2.1      
CacheControl                       0.12.5     
Cartopy                            0.17.0     
certifi                            2019.9.11  
cf-units                           2.1.1      
cffi                               1.12.2     
cftime                             1.0.3.4    
chardet                            3.0.4      
Click                              7.0        
click-plugins                      1.1.1      
cligj                              0.5.0      
cloudpickle                        0.8.0      
clyent                             1.2.2      
colorama                           0.4.1      
colorcet                           2.0.1      
comtypes                           1.1.7      
conda                              4.7.12     
conda-build                        3.17.8     
conda-package-handling             1.3.11     
conda-verify                       3.1.1      
contextlib2                        0.5.5      
cryptography                       2.5        
cycler                             0.10.0     
Cython                             0.29.6     
cytoolz                            0.9.0.1    
dask                               1.1.4      
datashader                         0.7.0      
datashape                          0.5.4      
decorator                          4.4.0      
defusedxml                         0.5.0      
descartes                          1.1.0      
distlib                            0.2.8      
distributed                        1.26.0     
docutils                           0.14       
eccodes                            2.10.2     
entrypoints                        0.3        
et-xmlfile                         1.0.1      
fastcache                          1.0.2      
filelock                           3.0.10     
Fiona                              1.8.4      
Flask                              1.0.2      
Flask-Cors                         3.0.7      
future                             0.17.1     
gast                               0.2.2      
GDAL                               2.3.3      
gensim                             3.8.1      
geopandas                          0.4.1      
geoviews                           1.6.5      
gevent                             1.4.0      
glob2                              0.6        
google-pasta                       0.1.7      
greenlet                           0.4.15     
grpcio                             1.24.1     
h5py                               2.9.0      
heapdict                           1.0.0      
holoviews                          1.12.6     
html5lib                           1.0.1      
hvplot                             0.5.2      
idna                               2.8        
imageio                            2.5.0      
imagesize                          1.1.0      
importlib-metadata                 0.0.0      
intake                             0.5.1      
ipykernel                          5.1.0      
ipyparallel                        6.2.4      
ipython                            7.4.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.4.2      
iris-grib                          0.13.0     
iris-sample-data                   2.1.0      
isort                              4.3.16     
itsdangerous                       1.1.0      
jdcal                              1.4        
jedi                               0.13.3     
Jinja2                             2.10       
jmespath                           0.9.4      
jsonschema                         3.0.1      
jupyter                            1.0.0      
jupyter-client                     5.2.4      
jupyter-console                    6.0.0      
jupyter-core                       4.4.0      
jupyterlab                         0.35.4     
jupyterlab-launcher                0.13.1     
jupyterlab-server                  0.2.0      
Keras-Applications                 1.0.8      
Keras-Preprocessing                1.1.0      
keyring                            18.0.0     
kiwisolver                         1.0.1      
lazy-object-proxy                  1.3.1      
libarchive-c                       2.8        
llvmlite                           0.28.0     
locket                             0.2.0      
lockfile                           0.12.2     
lxml                               4.3.2      
mapclassify                        2.0.1      
Markdown                           3.1.1      
MarkupSafe                         1.1.1      
matplotlib                         2.2.4      
mccabe                             0.6.1      
menuinst                           1.4.16     
mistune                            0.8.4      
mkl-fft                            1.0.10     
mkl-random                         1.0.2      
mkl-service                        2.0.2      
more-itertools                     6.0.0      
mpmath                             1.1.0      
msgpack                            0.6.1      
multipledispatch                   0.6.0      
munch                              2.3.2      
navigator-updater                  0.2.1      
nbconvert                          5.4.1      
nbformat                           4.4.0      
netCDF4                            1.5.1.2    
networkx                           2.2        
nltk                               3.4        
nose                               1.3.7      
notebook                           5.7.6      
numba                              0.43.0     
numexpr                            2.6.9      
numpy                              1.16.4     
numpydoc                           0.8.0      
odo                                0.5.1      
olefile                            0.46       
openpyxl                           2.6.1      
opt-einsum                         3.1.0      
OWSLib                             0.18.0     
packaging                          19.0       
pandas                             0.24.2     
pandocfilters                      1.4.2      
panel                              0.6.0      
param                              1.9.1      
parso                              0.3.4      
partd                              0.3.10     
path.py                            11.5.0     
pathlib2                           2.3.3      
patsy                              0.5.1      
pep8                               1.7.1      
pickleshare                        0.7.5      
Pillow                             5.4.1      
pip                                19.0.3     
pkginfo                            1.5.0.1    
pluggy                             0.9.0      
ply                                3.11       
progress                           1.5        
prometheus-client                  0.6.0      
prompt-toolkit                     2.0.9      
protobuf                           3.10.0     
psutil                             5.6.1      
psycopg2                           2.7.6.1    
pupygrib                           0.4.1      
py                                 1.8.0      
pycodestyle                        2.5.0      
pycosat                            0.6.3      
pycparser                          2.19       
pycrypto                           2.6.1      
pyct                               0.4.6      
pycurl                             7.43.0.2   
pyepsg                             0.4.0      
pyflakes                           2.1.1      
Pygments                           2.3.1      
pykdtree                           1.3.1      
pyke                               1.1.1      
pylint                             2.3.1      
pyodbc                             4.0.26     
pyOpenSSL                          19.0.0     
pyparsing                          2.3.1      
pyproj                             2.2.1      
pypyodbc                           1.3.4      
pyreadline                         2.1        
pyrsistent                         0.14.11    
pyshp                              2.1.0      
PySocks                            1.6.8      
pytest                             4.3.1      
pytest-arraydiff                   0.3        
pytest-astropy                     0.5.0      
pytest-doctestplus                 0.3.0      
pytest-openfiles                   0.3.2      
pytest-remotedata                  0.3.1      
python-dateutil                    2.8.0      
pytz                               2018.9     
pyviz-comms                        0.7.2      
PyWavelets                         1.0.2      
pywin32                            223        
pywinpty                           0.5.5      
PyYAML                             5.1        
pyzmq                              18.0.0     
QtAwesome                          0.5.7      
qtconsole                          4.4.3      
QtPy                               1.7.0      
requests                           2.21.0     
rise                               5.5.0      
rope                               0.12.0     
Rtree                              0.8.3      
ruamel-yaml                        0.15.46    
s3transfer                         0.2.1      
scikit-image                       0.14.2     
scikit-learn                       0.20.3     
scipy                              1.2.1      
scitools-iris                      2.2.1.dev0 
seaborn                            0.9.0      
selenium                           3.141.0    
Send2Trash                         1.5.0      
setuptools                         40.8.0     
Shapely                            1.6.4.post2
simplegeneric                      0.8.1      
singledispatch                     3.4.0.3    
six                                1.12.0     
smart-open                         1.8.4      
snowballstemmer                    1.2.1      
sortedcollections                  1.1.2      
sortedcontainers                   2.1.0      
soupsieve                          1.8        
Sphinx                             1.8.5      
sphinxcontrib-websupport           1.1.0      
spyder                             3.3.3      
spyder-kernels                     0.4.2      
SQLAlchemy                         1.3.1      
statsmodels                        0.9.0      
streamz                            0.5.1      
sympy                              1.3        
tables                             3.5.1      
tblib                              1.3.2      
tensorboard                        2.0.0      
tensorflow-estimator               2.0.0      
tensorflow-gpu                     2.0.0      
termcolor                          1.1.0      
terminado                          0.8.1      
testpath                           0.3.1      
thrift                             0.11.0     
toolz                              0.9.0      
tornado                            6.0.2      
tqdm                               4.31.1     
traitlets                          4.3.2      
typed-ast                          1.3.1      
typing                             3.6.4      
unicodecsv                         0.14.1     
urllib3                            1.24.1     
wcwidth                            0.1.7      
webencodings                       0.5.1      
Werkzeug                           0.14.1     
wheel                              0.33.1     
widgetsnbextension                 3.4.2      
win-inet-pton                      1.1.0      
win-unicode-console                0.5        
wincertstore                       0.2        
wrapt                              1.11.1     
xarray                             0.11.3     
xlrd                               1.2.0      
XlsxWriter                         1.1.5      
xlwings                            0.15.4     
xlwt                               1.3.0      
zict                               0.1.4      
zipp                               0.3.3

**Comment by philippjfr** [comment]
Seems to have been fixed with latest HoloViews.
