### ISSUE TITLE
Bug: "responsive mode could not be enabled because fixed width and height were specified" even though they are not specified

### ISSUE THREAD

**Issue by lsorber** [holoviz/hvplot#350]
#### ALL software version info

hvPlot 0.5.2
holoviews 1.12.6
bokeh 1.3.4
python 3.7.4
OS macOS
Browser Chrome

#### Description of expected behavior and the observed behavior

Expected: responsive plot rendered
Observed: empty plot + two warnings:
```
WARNING:param.PointPlot01664: responsive mode could not be enabled because fixed width and height were specified.
WARNING:param.PointPlot01664: aspect value was ignored because absolute width and height values were provided. Either supply explicit frame_width and frame_height to achieve desired aspect OR supply a combination of width or height and an aspect value.
```

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
from hvplot import hvPlot
import hvplot.pandas

df = pd.DataFrame(np.random.randn(10, 2), columns=['x', 'y'])
hvPlot(df).scatter(x="x", y="y", width=None, height=None).opts(responsive=True, aspect=4 / 3)
```

The warning message doens't make sense: the width and height are explicitly set to None. Removing the width and height arguments does render the plot, but the warning persists.

**Comment by philippjfr** [comment]
Sorry I never replied here, the responsive and aspect options should be passed to hvplot itself because otherwise hvPlot will set a width and height:

```python
hvPlot(df).scatter(x="x", y="y", responsive=True, aspect=4/3)
```

**Comment by jbednar** [comment]
It would be great if HoloViews could detect that the height and width were simply inherited from hvPlot and not explicitly set by the user, but I can't imagine any reasonable mechanism by which it could do so. :-(
