### ISSUE TITLE
hvplot.save gives AttributeError

### ISSUE THREAD

**Issue by kuchaale** [holoviz/hvplot#352]
#### ALL software version info 
hvPlot 0.5.2
holoviews 1.12.6
bokeh 1.3.4
python 3.6.8
OS Ubuntu
Browser Firefox

#### Description of expected behavior and the observed behavior
I would like to save an hvplot output using `hvplot.save`. While saving with bokeh renderer works, saving with `hvplot` does not work (see below). However, it may be an issue of `hvplot.xarray` since `hvplot.save` works when I use `hvplot.pandas` (see [here](https://gist.github.com/kuchaale/ac5eca8907dd57e5d62a1bb2bb3e677a)).

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import xarray as xr
import hvplot.xarray  # noqa
import holoviews as hv

air_ds = xr.tutorial.open_dataset('air_temperature').load()
air = air_ds.air
plot = air.hvplot(groupby='time', width=500)
renderer = hv.renderer('bokeh')
renderer.save(plot, 'test_xarray') # it works

hvplot.save(plot, 'test_xarray.html') # it does not work

```

#### Screenshots or screencasts of the bug in actiont
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-2f3a36a2f0e3> in <module>
----> 1 hvplot.save(plot, 'test_xarray.html')

/usr/local/lib/python3.6/dist-packages/hvplot/utilities.py in save(obj, filename, title, resources)
     40 
     41     if obj.traverse(lambda x: x, [_hv.HoloMap]):
---> 42         renderer.save(plot, filename)
     43     else:
     44         _save(plot, filename, title=title, resources=resources)

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/renderer.py in save(self_or_cls, obj, basename, fmt, key, info, options, **kwargs)
    543         else:
    544             with StoreOptions.options(obj, options, **kwargs):
--> 545                 plot = self_or_cls.get_plot(obj)
    546 
    547         if (fmt in list(self_or_cls.widgets.keys())+['auto']) and len(plot) > 1:

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/bokeh/renderer.py in get_plot(self_or_cls, obj, doc, renderer, **kwargs)
    133             curdoc().theme = self_or_cls.theme
    134         doc.theme = self_or_cls.theme
--> 135         plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
    136         plot.document = doc
    137         return plot

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/renderer.py in get_plot(self_or_cls, obj, renderer, **kwargs)
    184 
    185         # Initialize DynamicMaps with first data item
--> 186         initialize_dynamic(obj)
    187 
    188         if not isinstance(obj, Plot):

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/util.py in initialize_dynamic(obj)
    242     Initializes all DynamicMap objects contained by the object
    243     """
--> 244     dmaps = obj.traverse(lambda x: x, specs=[DynamicMap])
    245     for dmap in dmaps:
    246         if dmap.unbounded:

AttributeError: 'Figure' object has no attribute 'traverse'

**Comment by ahuang11** [comment]
tRY:

```
import xarray as xr
import hvplot.xarray  # noqa
import holoviews as hv

air_ds = xr.tutorial.open_dataset('air_temperature').load()
air = air_ds.air
plot = air.hvplot(groupby='time', width=500, dynamic=False)  # makes it a holomap
renderer = hv.renderer('bokeh')
renderer.save(plot, 'test_xarray') # it works

hvplot.save(plot, 'test_xarray.html') # it does not work
```

**Comment by kuchaale** [comment]
@ahuang11 Does it work for you? It gives the same error in my case. `hvplot.save` uses bokeh renderer anyway (see [hvplot/utilities.py#L42](https://github.com/pyviz/hvplot/blob/master/hvplot/utilities.py#L42)). [hvplot/utilities.py#L25](https://github.com/pyviz/hvplot/blob/master/hvplot/utilities.py#L25) makes the difference.
