### ISSUE TITLE
KeyError: 'glasbey_category10' - 

### ISSUE THREAD

**Issue by slamer59** [holoviz/hvplot#355]
With hvplot version : and colorcet version **0.9.1**

I have a KeyError : 
KeyError: 'glasbey_category10'

I check in https://github.com/pyviz/hvplot/blob/master/environment.yml

After update, it runs OK.

**Comment by jbednar** [comment]
It looks like some of the hvplot options default to `glasbey_category10` from colorcet, so yes, I do think colorcet is now a dependency.

**Comment by jsignell** [comment]
Closed by #356
