### ISSUE TITLE
Typing a string to input as crs/projection instead of a ccrs object similar to cmap/colors

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#363]
Instead of having to import `cartopy.crs as ccrs` and typing `projection=ccrs.Robinson()`, what if it could simply be `projection='Robinson'`, just like how you can enter `cmap='jet'` instead of `cmap=plt.cm.jet`?  Another example is the datetime strings and hover tool. Also, if so, not sure if it'd be good to have in geoviews or hvplot.

Implementation I think is straightforward
```
if isinstance(projection, str):
    projection = getattr(ccrs, projection)()
```

**Comment by philippjfr** [comment]
I wouldn't object to this, the logic should be added to `hvplot.util.process_crs`. Cc @jsignell @jbednar

**Comment by jbednar** [comment]
I have no objection, though it would need to be a bit more robust than above, i.e. to try to import `cartopy.crs` only if a string is supplied, and even then failing gracefully with a nice message like "Referring to projections by string name requires installing cartopy", if cartopy.crs is not importable.

**Comment by jsignell** [comment]
You can already pass a string to crs, but the string ins't an a cartopy class. It's a proj4 string - something like: 'EPSG:32618'. I don't think being able to pass the name of a cartopy class has much value since many require arguments an there would be no way to pass those.

**Comment by jsignell** [comment]
So I guess I'm -1 on this suggestion

**Comment by ahuang11** [comment]
I guess I am unfamiliar with proj4 strings. In most cases, I am simply projecting to GOOGLE_MERCATOR (for tiles) or Robinson (for global datasets) which require no additional arguments. If the user does want to provide additional arguments, it's similar to using `tools=[HoverTool()]`

**Comment by jbednar** [comment]
Seems like it's down to the details of an implementation, so I'd have to see that before deciding whether it's reliable enough to do this. E.g. one would have to first check proj4, have an exception, then try a Cartopy projection class name. Not crazy, but needs to not be confusing in practice.

**Comment by maximlt** [comment]
I'm also -1. GeoPandas uses `pyproj` under the hood to parse the value passed to the `crs` parameter when construction a GeoDataframe, this is what it currently accepts:

```
        PROJ string
        Dictionary of PROJ parameters
        PROJ keyword arguments for parameters
        JSON string with PROJ parameters
        CRS WKT string
        An authority string [i.e. ‘epsg:4326’]
        An EPSG integer code [i.e. 4326]
        A tuple of (“auth_name”: “auth_code”) [i.e (‘epsg’, ‘4326’)]
        An object with a to_wkt method.
        A pyproj.crs.CRS class
```

I'd expect hvPlot to go into that direction, instead of coming up with new ways.
