### ISSUE TITLE
Proposal for ECDF plot

### ISSUE THREAD

**Issue by ericmjl** [holoviz/hvplot#377]
**Is your feature request related to a problem? Please describe.**
It isn't. Rather, I would like to propose a new plot type.

**Describe the solution you'd like**
I would like to propose an ECDF plot.

The implementation is roughly as follows:

```python
def ecdf(df, column_name, **kwargs):
    assert df[column_name].dtype in [int, float]
    
    x, y = np.sort(df[column_name]), np.arange(1, len(df)+1) / len(df)
    
    label = kwargs.pop("label")
    plot_df = pd.DataFrame({column_name: x, "cumulative_fraction": y})
    return plot_df.hvplot.scatter(x=column_name, y="cumulative_fraction", label=label)
```

Happy to discuss where this would best be located.

**Comment by jbednar** [comment]
This would be best added in HoloViews, for which there is an issue already: https://github.com/holoviz/holoviews/issues/3821

**Comment by ericmjl** [comment]
Woohoo! By none other than @jsbois, who has been an advocate for this too! :smile:
