### ISSUE TITLE
Reference gallery has extra scroll bars

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#384]
When hovering at the edge, it creates extra scroll bars. Not a big deal, just wanted to report it's a bit awkward.
![image](https://user-images.githubusercontent.com/15331990/69823522-b7095a00-11ce-11ea-8385-7f04566c123c.png)

But it's a really nice reference gallery!

**Comment by philippjfr** [comment]
I'm not seeing this.

**Comment by ahuang11** [comment]
Still see it on a smaller monitor (aka laptop screen):
![image](https://user-images.githubusercontent.com/15331990/81236501-f54b4680-8fc2-11ea-8b17-7cbe19f5cd77.png)

**Comment by droumis** [comment]
I also don't see this in the latest chrome on macos monterey

@ahuang11 do you still see it? if so, what browser/os are you using?

**Comment by ahuang11** [comment]
Cannot reproduce anymore.
