### ISSUE TITLE
Add entrypoint for xarray

### ISSUE THREAD

**Issue by andersy005** [holoviz/hvplot#392]
Xarray is in the process of adding entrypoints for plotting backends in https://github.com/pydata/xarray/pull/3640. I took a look at https://github.com/holoviz/hvplot/pull/319 which added entrypoint support for Pandas, and I noticed that `.plot` method is for Tabular data only:

https://github.com/holoviz/hvplot/blob/a405ae7f44bcb9c85d907d7c8700acd5a2565e49/hvplot/plotting/__init__.py#L12-L14

https://github.com/holoviz/hvplot/blob/a405ae7f44bcb9c85d907d7c8700acd5a2565e49/hvplot/plotting/__init__.py#L32-L33

What's the right path to  adding the entrypoint for Xarray in hvplot? Should the `.plot` method in `hvplot/plotting/__init__.py` be 
extended/generalized in order to return instances of `hvPlot` class instead of `hvPlotTabular`?

With some guidance, I am happy to submit a PR that addresses this issue 😃

**Comment by philippjfr** [comment]
Thanks for working on this! Very happy to see it. I think we'll probably want a separate plot method just for xarray. I'm not entirely sure how to structure that yet. @jsignell do you have any good ideas?

**Comment by jsignell** [comment]
Sorry it took me so long to respond. Yes, a separate plot method is preferable.

**Comment by maximlt** [comment]
xarray has not implemented support for that.
