### ISSUE TITLE
Add keyword fontscale to hvplot

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/hvplot#395]
Fontscale works nicely in holoviews:
[https://github.com/holoviz/holoviews/issues/4107]( https://github.com/holoviz/holoviews/issues/4107)

This scales all fonts (title, labels, x-axis and y-axis etc.) in the plot simultaneously and saves time.

Can this feature also be added to hvplot?

I guess syntax would look something like:
```python
df.hvplot.scatter(
    x='x', 
    y='y', 
    fontscale=1.4,
)
```

**Comment by philippjfr** [comment]
Would you be willing to submit a PR?

**Comment by SandervandenOord** [comment]
I'm going to give it a try :)
