### ISSUE TITLE
Add 'sub_title' as another argument for plotting

### ISSUE THREAD

**Issue by corinnegroth** [holoviz/hvplot#396]
**Is your feature request related to a problem? Please describe.**
Yes.  I use data frames on a daily basis for projects, so my go-to plotting mechanism is to use hvplot.  I've been trying to place information mainly in the title of a plot, but the length of the title gets cut off after a certain point.

**Describe the solution you'd like**
I would like to have the ability to do something like this:
df.hvplot.line('x', 'y', title='Main info', sub_title='Secondary info'), 
where the sub_title goes below the main title, and it's above the plot itself.

**Describe alternatives you've considered**
There are a variety of solutions to this problem, but that requires changing my plots to be Holoviews, bokeh, or matplotlib plots, exclusively.  I don't want to change my plots to fit those styles JUST so that I have the capability to have a sub-title; that requires a lot of work, and my project(s) are on a time crunch.

**Comment by maximlt** [comment]
Bokeh now supports line breaks in a title so one can add as many lines as wanted in a plot.

**Comment by jmccreight** [comment]
A line break isnt a true subtitle, unless I'm missing how one change the font size for the different lines?
