### ISSUE TITLE
Scatter and Line-Scatter plots

### ISSUE THREAD

**Issue by gioarma** [holoviz/hvplot#398]
I have two problems regarding scatter plots with the pandas API, using `pd.options.plotting.backend = 'holoviews'` 

1. When I try to scatter plot a single column of a DataFrame, e.g. `df['col1'].plot(kind = 'scatter')`, I get the error: `plot kind scatter can only be used for data frames`. Why does this work if I plot all the columns of the DataFrame with `df.plot(kind = 'scatter')` while for a single column it doesn't?
I saw that by replacing `.plot()` with `.hvplot()` I get the expected result, but it is frustrating having to remember which method I have to use in which case.

2. I haven't found a way of simply getting a line+scatter plot, like the one you get with `'-o'` in matplotlib. For the moment what I do is overlaying with `*` two identical plots, but there must be a more clever way of doing this. Also, if I try to do this for plotting a single column of a DataFrame I get an error. For example 
`df['col1'].hvplot(kind = 'scatter')*df['col1'].hvplot() `
generates the error:
```
ERROR:bokeh.core.validation.check:E-1006 (NON_MATCHING_DATA_SOURCES_ON_LEGEND_ITEM_RENDERERS): LegendItem.label is a field, but renderer data sources don't match: LegendItem(id='3994', ...)
```
I think a `'kind = line_scatter'` option would be very nice.

**Comment by philippjfr** [comment]
1. Definitely seems like a bug.

2. Would definitely be nice to add support for that.

**Comment by maximlt** [comment]
I cannot reproduce the first issue and there are already issues dealing with the difficulty to customize line plots with markers a la matplotlib.
