### ISSUE TITLE
Plotting scatter from xarray dataset very slow

### ISSUE THREAD

**Issue by philippjfr** [holoviz/hvplot#399]
Scatter plot created from xarray Dataset very slow. In this example this takes 90 seconds

```python
import hvplot.xarray

ds = hv.Dataset((np.arange(611), np.linspace(0, 1, 11), np.random.randn(11, 611), np.random.randn(11, 611)), ['pos_int', 'Field'], ['Position', 'Signal'], datatype=['xarray'])
data = ds.data

obj = data.hvplot.scatter(x='Position', y='Signal', groupby=['Field'], dynamic=False)
```

While this takes less than a second:

```python
import hvplot.pandas

df = ds.data.to_dataframe()
obj = df.hvplot.scatter(x='Position', y='Signal', groupby=['Field'], dynamic=False)
```

**Comment by DancingQuanta** [comment]
Any progress on this?
The xarray hvplotting behaviour tried to make a overlay along `pos_int' dimension.
The trouble with the workaround is that the pandas dataframe do not take attribures from xarray objects which I need to label the plots.

**Comment by habemus-papadum** [comment]
Hi -- I am also encountering this issue.  

Furthermore, I am unclear exactly what `scatter` for a Dataset is suppose to mean.  Suppose `data.hvplot.scatter(x='x', y='y')`: If `x` and `y` are rank three tensors, my assumption is that if I do not specify a group `by`, the tensors will be flattened to vectors and then plotted, but something totally different happens, but I'm not sure.
