### ISSUE TITLE
Timeseries_Data.ipynb does not plot in colab

### ISSUE THREAD

**Issue by BitKnitting** [holoviz/hvplot#410]
Following code plots the first plot.  Future plots do not plot in colab.
works:
```
!pip install -U bokeh hvplot
import hvplot.pandas  # noqa
from bokeh.sampledata.sea_surface_temperature import sea_surface_temperature as sst
sst.hvplot()
```  
I can see the plot.  Now continue in the notebook:
```
scrampled = sst.sample(frac=1)
scrampled.hvplot()
```
It does not plot.

**Comment by jbednar** [comment]
There are workarounds for this issue for now; see https://github.com/holoviz/holoviews/issues/3551 .

**Comment by philippjfr** [comment]
This is indeed not an hvPlot issue and since it's captured at the HoloViews level I'll close.
