### ISSUE TITLE
apostrophe in df's object/string column breaks groupby

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#422]
```
pd.DataFrame({
    'locs': ["some apostrophe' place", 'no apostrophe'],
    'x': [1, 2], 'y': [5, 6]}
).hvplot.scatter(groupby='locs')
```
![image](https://user-images.githubusercontent.com/15331990/76687728-b1f0df00-65f4-11ea-97ed-da7765a86692.png)

**Comment by tonyfast** [comment]
![image](https://user-images.githubusercontent.com/4236275/88561091-f5c10f80-cffc-11ea-9770-e69fe261459c.png)

I was unable to reproduce this in hvplot 0.6.0 using firefox

**Comment by tonyfast** [comment]
@ahuang11 thanks for the issue, I wasn't able to reproduce.

Could you confirm that this is a problem in the most recent version of hvplot?

**Comment by philippjfr** [comment]
Suspect this was an issue with the old HoloViews widgets, which was resolved by upgrading to Panel based widgets.

**Comment by ahuang11** [comment]
It works now, thanks!
