### ISSUE TITLE
hvplot is not compatible with latest release of bokeh

### ISSUE THREAD

**Issue by yihming** [holoviz/hvplot#424]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
bokeh 2.0.0, python 3.7.6, hvplot 0.5.2

#### Description of expected behavior and the observed behavior
hvplot 0.5.2 is not compatible with bokeh 2.0.0, giving the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yy939/mgh/miniconda3/envs/pegasus-github/lib/python3.7/site-packages/hvplot/__init__.py", line 12, in <module>
    from .converter import HoloViewsConverter
  File "/Users/yy939/mgh/miniconda3/envs/pegasus-github/lib/python3.7/site-packages/hvplot/converter.py", line 25, in <module>
    from holoviews.plotting.bokeh import OverlayPlot
  File "/Users/yy939/mgh/miniconda3/envs/pegasus-github/lib/python3.7/site-packages/holoviews/plotting/bokeh/__init__.py", line 30, in <module>
    from .annotation import (TextPlot, LineAnnotationPlot, SplinePlot,
  File "/Users/yy939/mgh/miniconda3/envs/pegasus-github/lib/python3.7/site-packages/holoviews/plotting/bokeh/annotation.py", line 23, in <module>
    from .element import AnnotationPlot, ElementPlot, CompositeElementPlot, ColorbarPlot
  File "/Users/yy939/mgh/miniconda3/envs/pegasus-github/lib/python3.7/site-packages/holoviews/plotting/bokeh/element.py", line 23, in <module>
    from bokeh.plotting.helpers import _known_tools as known_tools
ModuleNotFoundError: No module named 'bokeh.plotting.helpers'
```
But it's compatible with bokeh 1.4.0.
#### Complete, minimal, self-contained example code that reproduces the issue

```
pip install --upgrade hvplot
pip install --upgrade bokeh
python
>>> import hvplot
```

**Comment by epifanio** [comment]
The import issue 

```python
from bokeh.plotting.helpers import _known_tools as known_tools
ModuleNotFoundError: No module named 'bokeh.plotting.helpers'
```
could be replaced with:
```python
from bokeh.plotting._tools import TOOLS_MAP as known_tools
```

Which gives the next API change issue:

```
import hvplot.pandas

...python
from bokeh.embed.notebook import encode_utf8, notebook_content
ImportError: cannot import name 'encode_utf8' from 'bokeh.embed.notebook' 
```

From the [Bokeh 2.0.0 release list of changes](https://github.com/bokeh/bokeh/blob/b9a66333e3d6b9508e5e58aa05e8ea1a9a91780e/sphinx/source/docs/releases/2.0.0.rst) I see:  

- `bokeh.util.string` Functions `encode_utf8`, `decode_utf8`, and `escape` removed

**Comment by philippjfr** [comment]
This has already been fixed in HoloViews and will be addressed once HoloViews 1.13.0 is out (see https://github.com/holoviz/holoviews/issues/4293).

**Comment by yihming** [comment]
Thank you so much for your clarification!

**Comment by michaelaye** [comment]
I'm confused, this issue has been closed, and I have Holoviews 1.13.0, so this should be working? I thought @philippjfr 's comment only meant that this WILL BE addressed in `hvplot` once Holoviews 1.13 is out?

**Comment by philippjfr** [comment]
This should definitely be fixed as of the HoloViews 1.13 release, i.e. it should be working now.

**Comment by yihming** [comment]
Yes. My case works now.

**Comment by michaelaye** [comment]
can't make it work on linux, works on mac in JLab though, despite not having pyviz/jupyterlab_pyviz, but docs say it's needed, confusing. Will make a new issue.

**Comment by philippjfr** [comment]
Strange, let us know what you find. jupyterlab_pyviz is only needed for comms and therefore interactive features relying on the jupyter kernel to work.

**Comment by michaelaye** [comment]
Looks like it's a Bokeh problem, will report there.

<img width="759" alt="Screenshot 2020-03-23 20 44 53" src="https://user-images.githubusercontent.com/69774/77382953-538bd500-6d47-11ea-955c-c0323c66d206.png">

**Comment by philippjfr** [comment]
Looks like the extension wasnt loaded so probably a HoloViews issue if anything.

**Comment by michaelaye** [comment]
gosh, i wish i could tell you yet if it's Holoviews but it's amazingly hard to find a simple data example code cell that doesn't depend on the assets folder. holoviews' very first example notebook depends on it, but it doesn't say in that notebook what needs to be done to have that assets folder available. :(

**Comment by michaelaye** [comment]
ok, found it, i was looking for an "installation" section, but because my screen height was just optimally cutting off the main page below the example graphics, the installation section on that page was "invisible" to me. :) Maybe would be good to add a general installation pointer in a TOC somewhere..
Now trying the examples...

**Comment by michaelaye** [comment]
ok, now i'm stumped. no errors with bokeh itself, and no errors with Holoviews, so why does hvplot create above errors?
of course, retrying the hvplot example now, it works. Is there such thing as bokeh needs to be run once before it works maybe? Sorry for the noise...
