### ISSUE TITLE
heatmap labels reorder

### ISSUE THREAD

**Issue by narudarurarasya** [holoviz/hvplot#425]
Hello, 

 I have a heatmap that I'd like to re-order the xlabels of. With bokeh I can get the plot object and do that with ```p.x_range.factors = ['morning', 'daytime', 'evening', 'night', 'NA']``` but I have no idea with holoviews.

```df.hvplot.heatmap('cluster_2', 'cluster_1', 'size')``` gives me this:

<img width="722" alt="heatmap" src="https://user-images.githubusercontent.com/6368653/69336450-d64c3880-0c5e-11ea-97d7-3a1fe2a67eae.png">

and I want to set the order as e.g., `['morning', 'daytime', 'evening', 'night', 'NA']` !

Any help would be great.

Thanks!

**Comment by jlstevens** [comment]
Given the way `hvplot` works, imposing the order you want on the dataframe/xarray seems to be the right way to do it. As such this looks like a usage issue (and please do post to [discourse](https://discourse.holoviz.org/) if you have more questions) which means I think this issue can now be closed.
