### ISSUE TITLE
Plot Title Warning

### ISSUE THREAD

**Issue by gioarma** [holoviz/hvplot#426]
#### Software version info
holoviews 1.13.0
bokeh 2.0.0
JupyterLab 2.0.1

#### Example code

```python
import pandas as pd
import hvplot.pandas
pd.options.plotting.backend = 'holoviews'

df = pd.DataFrame(range(5))
df.plot(title = 'Test')
```
I get the plot, but also a warning: 

```
WARNING:param.OverlayPlot23109: title_format is deprecated. Please use title instead
```
although I'm using `title`, not `title_format`

**Comment by philippjfr** [comment]
Thanks, we'll get a new hvPlot release out soon which will use title internally.

**Comment by otro-mas1** [comment]
try change line 
`df.plot(title = 'Test') ===> df.plot().opts(title='Test')`

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/hvplot/pull/428. Will try to get a release out asap.

**Comment by philippjfr** [comment]
Sorry for the delay here, I'm trying to get this release out today.
