### ISSUE TITLE
axis ranges are not set when using bar plot with plotly backend

### ISSUE THREAD

**Issue by realalexgalenko** [holoviz/hvplot#427]
Hello,

First, thank you for the awesome library! Really like it. It is super easy to prototype things, my only complain - drawing interactive graphs using bokeh seems way too slow. Plotly redraws everything much quicker. So I tried using plotly as backend in panel and holoviews and having some formatting issues which I guess expected. I also saw in your roadmap you would like to expand plotly support, so I decided to post some issues I have found so far.

I get weird plots when using plotly as backend with bar plots. 

#### ALL software version info
appnope==0.1.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.1
bokeh==1.4.0
certifi==2019.11.28
chardet==3.0.4
click==7.1.1
cloudpickle==1.3.0
colorcet==2.0.2
cycler==0.10.0
dask==2.12.0
datashader==0.10.0
datashape==0.5.2
decorator==4.4.2
defusedxml==0.6.0
distributed==2.12.0
entrypoints==0.3
fsspec==0.6.2
HeapDict==1.0.1
holoviews==1.12.7
hvplot==0.5.2
idna==2.9
imageio==2.8.0
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.1
json5==0.9.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.0.0
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==2.0.1
jupyterlab-server==1.0.7
kiwisolver==1.1.0
llvmlite==0.31.0
locket==0.2.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.0
mistune==0.8.4
msgpack==1.0.0
multipledispatch==0.6.0
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
notebook==6.0.3
numba==0.48.0
numpy==1.18.1
packaging==20.3
pandas==1.0.2
pandocfilters==1.4.2
panel==0.8.1
param==1.9.3
parso==0.6.2
partd==1.1.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
plotly==3.8.0
prometheus-client==0.7.1
prompt-toolkit==3.0.4
psutil==5.7.0
ptyprocess==0.6.0
pyct==0.4.6
Pygments==2.6.1
pyparsing==2.4.6
pyrsistent==0.15.7
python-dateutil==2.8.1
pytz==2019.3
pyviz-comms==0.7.4
PyWavelets==1.1.1
PyYAML==5.3
pyzmq==19.0.0
qtconsole==4.7.1
QtPy==1.9.0
requests==2.23.0
retrying==1.3.3
scikit-image==0.16.2
scipy==1.4.1
Send2Trash==1.5.0
six==1.14.0
sortedcontainers==2.1.0
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.4
tqdm==4.43.0
traitlets==4.3.3
typing-extensions==3.7.4.1
urllib3==1.25.8
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
xarray==0.15.0
zict==2.0.0
zipp==3.1.0

#### Description of expected behavior and the observed behavior
When I use scatter plot (see code below) - axis scale properly:

![image](https://user-images.githubusercontent.com/56047454/77354610-1d336300-6d11-11ea-8429-4d5eba4add87.png)

When I switch from scatter to bar - it shows this (x axis range goes only to 4)

![image](https://user-images.githubusercontent.com/56047454/77354666-34725080-6d11-11ea-9b86-f2c6b0ed015a.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import hvplot.pandas
import holoviews as hv
import pandas as pd
hv.extension('plotly', logo=False)
tmp_df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [1000, 200, 1, 800]},
                  index=['falcon', 'dog', 'spider', 'fish'])
tmp_df.hvplot(kind='scatter',x='num_specimen_seen',y='num_legs', height=200, width=200)
tmp_df.hvplot(kind='bar',x='num_specimen_seen',y='num_legs', height=200, width=200)

```

**Comment by jbednar** [comment]
Right; hvPlot only currently supports a Bokeh backend.  You are welcome to use it with other HoloViews backends, but then you would need to set up all of the options and settings manually, as there is only currently machinery in there to translate those options and settings into the form Bokeh plots accept.  If there is a community of Plotly users who want hvPlot support, building up such translations shouldn't be a huge effort, but it definitely _is_ an effort and not something that I know anyone is starting on in the near future.

**Comment by realalexgalenko** [comment]
got it, thanks for clarification @jbednar

**Comment by philippjfr** [comment]
Going to close, given that this is explicitly not supported right now and adding support is covered by https://github.com/holoviz/hvplot/issues/156.
