### ISSUE TITLE
hvplot xlim, ylim error

### ISSUE THREAD

**Issue by shj69** [holoviz/hvplot#440]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
hvplot 0.5.2

#### Description of expected behavior and the observed behavior
wanted to set the xlim and ylim values; for some values the map comes up as expected, for some values it produces error messages - unclear to me why.

#### Complete, minimal, self-contained example code that reproduces the issue
THIS CODE WORKS:

```
import hvplot.pandas  # noqa
df = gdf[intermedia].copy()
df['x'] = df.geometry.x
df['y'] = df.geometry.y
df = pd.DataFrame(df)

minx = (df['x'].min())
maxx = (df['x'].max())
miny = (df['y'].min())
maxy = (df['y'].max())
df.hvplot.points('x', 'y', geo=True, color='red', alpha=0.2, tiles='ESRI')
```
![hvplot_works](https://user-images.githubusercontent.com/52162580/78878772-38150f80-7a53-11ea-8738-43bc752330e9.jpg)
![hvplot_works2](https://user-images.githubusercontent.com/52162580/78878778-39463c80-7a53-11ea-8527-821cf62bb56d.jpg)

THIS CODE DOES NOT WORK:

```
df.hvplot.points('x', 'y', geo=True, color='red', alpha=0.2, xlim=(xmin,xmax), ylim= (ymin, ymax), tiles='ESRI')
```

Solution / workaround:
```
gdf.hvplot.points(geo=True, color='red', alpha=0.2).options(xlim=(minx, maxx), ylim=(miny, maxy))
```

**Comment by maximlt** [comment]
I'm going to close this issue as it's unfortunately missing a reproducible example and the error messages mentioned. There are for sure usage difficulties/bugs with xlim/ylim in a geo plot, which are captured in other issues.
