### ISSUE TITLE
allow color_key an alias for cmap

### ISSUE THREAD

**Issue by itcarroll** [holoviz/hvplot#444]
The ability to pass cmap dicts through to datashader color_key was solved in the fix for #267, but it may be good to also accept `color_key` as an argument. See https://discourse.holoviz.org/t/keyed-color-map-for-image/505.

BTW, @jsignell mentioned in the fix the need to think about the legend ... which would be great to have too.

**Comment by jsignell** [comment]
That seems like a reasonable suggestion. Would you be willing to open a PR?

**Comment by itcarroll** [comment]
Maybe. Can you can point me to an example of the pythonic way to alias a kwarg, one that changes the documentation correctly too?

**Comment by jsignell** [comment]
Cool! You'll want to mimic what's going on with `colormap` in this file: https://github.com/holoviz/hvplot/blob/master/hvplot/converter.py
