### ISSUE TITLE
kde colour sequence does not match line and hist

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/hvplot#468]
![image](https://user-images.githubusercontent.com/31582215/82842006-e9012d80-9e8c-11ea-9598-fd3accf9154a.png)

Notice that KDE has inverted colours. Is this a bug?

Thanks!
Ygg

**Comment by philippjfr** [comment]
Certainly strange.

**Comment by LinuxIsCool** [comment]
Code to reproduce:


```
import numpy as np
import pandas as pd
import hvplot.pandas

size=400

y_target = np.random.normal(0,1.5,size)
y_predictions = np.random.normal(1,1,size)
performance = pd.DataFrame(list(zip(y_target,y_predictions)),columns=['y_target','y_predictions'])

(performance.hvplot.line() + performance.hvplot.kde(alpha=0.8) + performance.hvplot.hist(bins=40, alpha=0.8)).cols(1)
```
Result:

![image](https://user-images.githubusercontent.com/31582215/82853548-ed443f80-9eba-11ea-94a9-a81beb751540.png)
