### ISSUE TITLE
Documentation: hvnx.draw parameter node_color works better than documented

### ISSUE THREAD

**Issue by johann-petrak** [holoviz/hvplot#471]
Version 0.5.2

The parameter `node_color` of the function hvnx.draw has documentation:
```
node_color : color string, or array of floats, (default='r')
   Node color. Can be a single color format string,
   or a  sequence of colors with the same length as nodelist.
   If numeric values are specified they will be mapped to
   colors using the cmap and vmin,vmax parameters.  See
   matplotlib.scatter for more details.
```

However, if I set this to a string which is not a color name, and that string is an attribute of my nodes, then the values of that attribute are used, which is great! But not mentioned in the documentation.

Also, if the parameter is set to a string which is neither a colour name nor the name of an attribute, then no output but also not exception or error message is produced.

Example:
```
import networkx as nx
import hvplot.networkx as hvnx

nodes = [1,2,3,4,5,6,7,8,9,10]
edges = [(1,2), (1,3), (1,4), (4,5), (4,3), (8,9), (8,7), (7,6)]

nxg1 = nx.Graph()
nxg1.add_nodes_from(nodes)
nxg1.add_edges_from(edges)
pos = nx.spring_layout(nxg1)

# some attributes for the nodes
for node in nxg1.nodes:
    nxg1.nodes[node]["label"] = f"Node{node}"
    nxg1.nodes[node]["desc"] = "some description"
    nxg1.nodes[node]["color"] = ["blue","yellow"][node%2]
hvnx.draw(nxg1, pos, node_color="color", hover_cols="all")
```

If `node_color="dfsdfd"` is used instead, no output and no error is generated.

**Comment by LinuxIsCool** [comment]
It would be amazing if `node_line_color` had the same versatile functionality as `node_color`.
