### ISSUE TITLE
Warning: title_format is deprecated

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#473]
ORIGINALLY POSTED HERE https://github.com/holoviz/holoviz/issues/257

SIMILAR PROBLEM POSTED HERE https://github.com/holoviz/panel/issues/1184

-----------------

HoloViz:  0.11.3
hvplot: 0.5.2
HoloViews:  1.13.2

#### My Pain

Trying to use the HoloViz tutorial for a course. There is a lot of new things to learn for my users so I would like to make the learning experience as smooth as possible.

One area of friction is this deprecation warning in the 05_Composing_Plots.ipynb notebook

```bash
WARNING:param.CurvePlot03050: title_format is deprecated. Please use title instead
```

![image](https://user-images.githubusercontent.com/42288570/83400185-b615e700-a402-11ea-9548-9abd255485b7.png)

**Comment by gioarma** [comment]
I already posted this in the hvplot repo: holoviz/hvplot#426
As you can see I got an answer and the fix should be out with the next update from what I understood
