### ISSUE TITLE
Execution of a `notebook.py` file

### ISSUE THREAD

**Issue by kfilipan** [holoviz/hvplot#485]
#### ALL software version info

Windows 10 1909 x64
Chromium 83.0.4103.0

Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.3
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.6
traitlets        : 4.3.3

```
>>> hvplot.__version__
'0.5.2'
>>> holoviews.__version__
'1.13.2'
```

#### Description of expected behavior and the observed behavior

If you have a `notebook.py` file in a folder where your Jupyter notebook resides, when executing e.g. `import hvplot.xarray` or `hvplot.pandas` you will also execute the contents of the `notebook.py` file.

#### Complete, minimal, self-contained example code that reproduces the issue

1. Create a Python file `notebook.py` with a single line:

```
print('THIS IS EXECUTED')
```

2. Create a Jupyter notebook with any name and put a single line into it:

```
import hvplot.xarray
```

3. Execute a Jupyter notebook.

Minimal example in the 
[test-example.zip](https://github.com/holoviz/hvplot/files/4807849/test-example.zip)

#### Screenshots or screencasts of the bug in action

The output of this test for me is as follows:

![bug](https://user-images.githubusercontent.com/43028531/85201568-d0a3f780-b300-11ea-8318-0c93efbf2478.png)

**Comment by kfilipan** [comment]
This bug could be repeated on my other computer with the following software installed:

Windows 10 1909 x64

VSCodium 1.46.0
Chromium 83.0.4103.0

Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.7.2
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.0.0
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

```
>>> hvplot.__version__
'0.5.2'
>>> holoviews.__version__
'1.12.7'
```

**Comment by tonyfast** [comment]
I am pretty sure this a name collision with the [`notebook`](https://pypi.org/notebook). If I modify the name of the script, I can't reproduce the behavior above.

This error should vanish if `notebook.py` were in a package that could use relative imports.

**Comment by tonyfast** [comment]
Feel free to reopen if you think this is something other than a name collision.
