### ISSUE TITLE
shared_axes=False not fully taken into account with datashade=True

### ISSUE THREAD

**Issue by marcbernot** [holoviz/hvplot#486]
hvplot=0.6
datashader=0.11
holoviews=1.13.2 & 1.13.3

I observe a change of output of the following code between holoviews 1.13.2 and 1.13.3. 

```
df = pd.DataFrame(dict(a=[1,2],b=[3,4]))
df.hvplot(subplots=True,shared_axes=False,datashade=True,width=300)
```
What would be expected is to have the same initial axes as the output of ```df.hvplot(subplots=True,shared_axes=False,datashade=False,width=300)```
![nodatashade](https://user-images.githubusercontent.com/8888261/85726011-f90f6580-b6f5-11ea-862a-90c488d96f97.png)

Notice that this latter line of code yields the same (expected) result with both 1.13.2 and 1.13.3.

However, with datashade=True and 1.13.3, the axes are 'half-shared' in the sense that the zoom interaction can be carried out independantly on both axes BUT they have the same range initially.
 
The output of ```df.hvplot(subplots=True,shared_axes=False,datashade=True,width=300)```

with holoviews 1.13.2 (as expected)

![datashade_holoviews_1_13_2](https://user-images.githubusercontent.com/8888261/85729651-493bf700-b6f9-11ea-958d-b872d4e80932.png)

with holoviews 1.13.3 (not as expected)

![datashade_holoviews1_13_3](https://user-images.githubusercontent.com/8888261/85729914-7ee0e000-b6f9-11ea-87f1-e0b7691a1d55.png)

**Comment by tonyfast** [comment]
Perhaps this is a concern to #495

**Comment by jlstevens** [comment]
Definitely sounds like a bug to me, especially given that you have helpfully pinned down the difference in behaviour between  holoviews 1.13.2 and 1.13.3.

**Comment by marcbernot** [comment]
I revisited this bug, it looks it disappeared with holoviews=1.14.0
It is also no longer present with a fresh install : 
holoviews=1.14.8
panel=0.12.7
hvplot=0.7.3
datashader=0.13
