### ISSUE TITLE
Would like Geopandas hvplot and not have to have 'geometry' as the geometry name

### ISSUE THREAD

**Issue by ayoungs** [holoviz/hvplot#508]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### Is your feature request related to a problem? Please describe.
With a GeoDataFrame, I can't have a name of my choosing for the geometry.
posd={'position':[Point(-100,40),Point(-120,42)]}
myTestDF = gpd.GeoDataFrame(posd,geometry='position')
myTestDF.hvplot()
I get an error doing that.
I have to rename.

#### Describe the solution you'd like
I'd like to get a plot without doing a rename on the geometry.
posd={'position':[Point(-100,40),Point(-120,42)]}
myTestDF = gpd.GeoDataFrame(posd,geometry='position')
myTestDF.hvplot()

#### Describe alternatives you've considered
This snippet of code works by renaming geometry column to 'geometry'
posd={'position':[Point(-100,40),Point(-120,42)]}
myTestDF = gpd.GeoDataFrame(posd,geometry='position')
myTestDF.rename_geometry('geometry',inplace=True)
myTestDF.hvplot()

**Comment by maximlt** [comment]
This issue has been fixed in GeoViews, this now works:

```python
import hvplot.pandas
import geopandas as gpd
from shapely.geometry import Point

posd={'position':[Point(-100,40),Point(-120,42)]}
myTestDF = gpd.GeoDataFrame(posd,geometry='position')

myTestDF.hvplot()
```
