### ISSUE TITLE
'fire' as pandas dataframe column throws ValueError with hvplot.scatter(y='fire')

### ISSUE THREAD

**Issue by matsvandecavey** [holoviz/hvplot#518]
#### software version info
pandas                   1.1.3
holoviews               1.13.4
hvplot                    0.6.0 
jupyterlab               2.2.6

```python
columns = ['earth','water','air','fire']
df = pd.DataFrame(data=np.random.rand(100,4)*np.random.randint(1,6,(1,4)),
                                            columns=columns)

df.hvplot.scatter(y='fire')
``` 
throws unexpected <code>ValueError</code> in jupyter notebook and jupyter lab.

>ValueError [Call holoviews.ipython.show_traceback() for details]
>Mapping a dimension to the "cmap" style option is not supported by the Scatter element using the bokeh backend. To map the >"fire" dimension to the cmap use a groupby operation to overlay your data along the dimension.

```python
hv.ipython.show_traceback()
```
>Traceback (most recent call last):
>  File "C:\....\Continuum\anaconda3\envs\dc-cds\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1323, in _init_glyphs
>       style = self._apply_transforms(element, data, ranges, style)
>  File "C:\....\Continuum\anaconda3\envs\dc-cds\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1092, in _apply_transforms
>      backend=self.renderer.backend))
>ValueError: Mapping a dimension to the "cmap" style option is not supported by the Scatter element using the bokeh backend. To map the "fire" dimension to the cmap use a groupby operation to overlay your data along the dimension.

Similar code has no issues! 
```
df.hvplot.scatter(y=['air','fire'])  # OK
df.hvplot.line(y='fire')  # OK
```

**Comment by maximlt** [comment]
I can't reproduce.
