### ISSUE TITLE
matplotlib now completely broken with hvplot

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#520]
It used to work for the most part
```
import xarray as xr
import hvplot.xarray
import holoviews as hv
hv.extension('matplotlib')
ds = xr.tutorial.open_dataset('air_temperature').isel(lat=0, lon=0)
ds.hvplot('lon', 'lat')
```

But now it errors out:

`ValueError: Unexpected option 'height' for Curve type when using the 'matplotlib' extension. No similar options founds.`

**Comment by jbednar** [comment]
Oh, thanks for that report! I'd noticed the same thing, and I did think that it used to work better than that. Glad to see I wasn't crazy. @philippjfr , presumably the `backend="bokeh"` specifier could be applied whenever adding options to the HoloViews objects that get constructed?  That might get highly verbose, but would make it explicit that they are for Bokeh and let us gradually patch in support for other backends...

**Comment by m-beau** [comment]
Hi,

My scripts are also completely messed up, it is a real annoyance. I had setup a very specific set of matplotlib-only parameters to be able to make my plots with hvplot, so there is no workaround for me. Please let us know when this issue is fixed.

**Comment by jbednar** [comment]
Just to be clear, this is unsupported usage of hvPlot, so it's not an issue to be fixed, but an (optional) improvement that could be made. Much as we would like it to, hvPlot has never promised to support Matplotlib (or Plotly) output. In the absence of funding or a volunteer to do that, any hvPlot issues to do with Matplotlib or Plotly are just wishlist items. 

If anyone who is using matplotlib with hvplot is willing to search the source code for where options are being set and specify `backend='bokeh'` on any bokeh-specific ones, that would be a great way to contribute and would help you get things working again. The core maintainers are all fully allocated just trying to support Bokeh usage, and can't also take on Matplotlib usage at this time.

**Comment by philippjfr** [comment]
What's really needed here is an "options transformer". Once implemented could simply drop all the unsupported options initially and then slowly be made to translate more options until we have rough compatibility between backends. I imagine that we'll need to refactor some of the internals to come up with a generic options specification that can then be transformed by all the backend specific transformers.

**Comment by ahuang11** [comment]
@m-beau A quick fix would be adding the following on line 1301 in hvplot/hvplot/converter.py.
```
        try:
            return chart.redim(**self._redim).opts(opts)
        except:
            backend_options = Store.options(backend='matplotlib')
            objtype = element.name
            opts = {key: val for key, val in opts.items() if key in backend_options[objtype]}
            return chart.redim(**self._redim).opts(opts)
```
Not sure if the jbednar/philippjfr want this quick patch as a PR for semi-usability with matplotlib while the bigger conversion PR happens. If so, I can convert this function as a util and insert every where .opts() is called in converter.py

```
import xarray as xr
import hvplot.xarray
import holoviews as hv
hv.extension('matplotlib')
ds = xr.tutorial.open_dataset('air_temperature').isel(lat=0, lon=0)
ds.hvplot('time').opts(fig_size=200)
```
![image](https://user-images.githubusercontent.com/15331990/109741065-f7097a80-7b91-11eb-85e1-c39b88e40c75.png)

**Comment by jbednar** [comment]
Thanks! I'll leave that up to @philippjfr to decide, but I'm ok with it.  I'd be concerned about strange behavior for cases where both backends define an option with the same name but interpret it differently, e.g. `size` in pixels vs. `size` in inches.

**Comment by ahuang11** [comment]
By the way, how do you imagine the "options transformer" would work? A giant dictionary containing all the translations?

e.g. in holoviews/holoviews/util/__init__.py line 370:
```
    @classmethod
    def _expand_options(cls, options, backend=None):
        """
...
                TRANSLATIONS = {
                    'matplotlib': {
                        'height': 'fig_inches',
                        'width': 'fig_inches',
                        'line_width': 'linewidth',
                        'muted_alpha': False,
                        'responsive': False,
                        'shared_axes': False,
                        'tools': False
                    }
                }
                for g, group_opts in sorted(obj_options.groups.items()):
                    if opt in group_opts.allowed_keywords:
                        expanded[objspec][g][opt] = value
                        found = True
                        break
                    elif opt in TRANSLATIONS[backend]:
                        translated_opt = TRANSLATIONS[backend][opt]
                        options[translated_opt] = options.pop(opt)
                        found = True
                        break
```
Some are directly translatable like line_width to linewidth, but fig_inches needs both width + height.

**Comment by m-beau** [comment]
Thank you so much for working on this issue!

An automatic matplotlib-bokeh options translator would be an absolute dream, ideally with a printed warning whenever an option is automatically translated from one to another in the background to teach the user how to harness explicitly bokeh vs matplotlib as he/she gets to use your package. Most of us (computational biologist speaking here!) learn python using matplotlib, and then discover the power of interactive/web-based plotting of bokeh, which is more complex to use. Holoviews has been a user friendly, grammar-of-graphics-oriented much welcome bridge between both for me.

I didn't know that matplotlib wasn't officially supported, but if matplotlib support becomes more stable in the future, holoviews (and its frontend hvplot) would beautifully address the problem of getting close to a complex end result fast -> tweaking the plot to get to the exact desired end result philosophy that I heard your team describe in talks. Which completely turned me on, I must confess.

**Comment by jbednar** [comment]
Just to be clear, Matplotlib *is* fully supported by HoloViews and by Panel; it's simply not supported by hvPlot. hvPlot is an alternative API for HoloViews that maps from options specified into a certain form that was defined by Pandas into HoloViews options for the Bokeh backend. We can do the same sort of mapping for any other backend, but currently have neither funding nor volunteers for doing that. So we do _not_ support Matplotlib for hvPlot _currently_, but that could change if we get either funding or a volunteer to work with us to do that mapping.

**Comment by maximlt** [comment]
hvPlot now supports Matplotlib as an additional backend.
