### ISSUE TITLE
invert_yaxis=True not working with bokeh backend ? 

### ISSUE THREAD

**Issue by lhoupert** [holoviz/hvplot#536]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
hvplot:0.7.0
xarray:0.16.2

#### Description of expected behavior and the observed behavior
Expected behavior:
![Screenshot 2020-12-15 at 15 20 51](https://user-images.githubusercontent.com/10154151/102226799-bed29400-3ee0-11eb-96a9-051e9c1bd2a9.png)

Observed behavior:
![Screenshot 2020-12-15 at 15 21 34](https://user-images.githubusercontent.com/10154151/102226886-d7db4500-3ee0-11eb-98f5-754541d549b8.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```python3
import xarray as xr
import hvplot.xarray
import holoviews as hv

np.random.seed(1)
refdist = np.array(range(100,1000,100))
depth = np.array(range(5,30,10))
data = np.random.uniform(low = -5, high = 5, size = (len(refdist), len(depth)))

ds = xr.Dataset(
    {   "V": (["refdist", "depth"], data),
    },
    coords={
        "refdist": (refdist),
        "depth": (depth),
    },
)


cf=ds['V'].hvplot.contourf(z='V', x='refdist', y='depth', levels=10)
cf

```

```python3
cf.opts(invert_yaxis=True)
```

`invert_yaxis=True` doesn't change the orientation of the plot cf

**Comment by jbednar** [comment]
I believe if you roll back Panel to an earlier release this should be fixed; can't recall which version. Should also be fixed in the next Panel release, but that's not out yet.

**Comment by lhoupert** [comment]
@jbednar do you mean `hvplot`?

**Comment by jbednar** [comment]
No, Panel. There's a Panel issue that affects HoloViews and hvPlot layouts. I'm in meetings all day or I'd look it up. :-/

**Comment by MarcSkovMadsen** [comment]
Is there a workaround we can use until a new version of Panel has been released? My problem is with `invert_xaxis`.

**Comment by jlstevens** [comment]
Panel 0.10.3 has now been released and it looks like it is working to me:

![image](https://user-images.githubusercontent.com/890576/106491839-e5db2a00-647c-11eb-9f83-65d9160ac899.png)

I'll close this issue now but please don't hesitate to post a comment if you think there is still a problem after using more recent panel versions.
