### ISSUE TITLE
I love coastline=True.  Could we also have borders=True, states=True, rivers=True ?

### ISSUE THREAD

**Issue by rsignell-usgs** [holoviz/hvplot#540]
I love the convenience of `coastline=True` in hvplot. 

Would it be straightforward to add the rest of the very common feature types from: https://scitools.org.uk/cartopy/docs/latest/matplotlib/feature_interface.html#cartopy.feature ?

![2020-12-23_7-05-51](https://user-images.githubusercontent.com/1872600/102994794-c3ed9f80-44ed-11eb-9c70-f01b8816a941.png)

**Comment by philippjfr** [comment]
Maybe `features=` which accepts one or more of those as strings?

**Comment by jlstevens** [comment]
Seconded!

The only thing I would say is if `features` is supported, I would eventually deprecate the `coastline` keyword.

**Comment by ahuang11** [comment]
`features` has been implemented, I think this could be closed?
