### ISSUE TITLE
Installation with Conda creates Bokeh Errors

### ISSUE THREAD

**Issue by LoriHarris** [holoviz/hvplot#564]
It seems that installing hvplot with `conda install -c pyviz hvplot` now installs `bokeh versions 2.3` . This seems to cause errors when using Jupyter Lab and `hvplot.pandas`. Example:

The following code:
```
df.hvplot.line()

```
If using bokeh version 2.3, cell output:
![image](https://user-images.githubusercontent.com/43394481/109712487-17bfd900-7b6e-11eb-9267-4e2679e880b2.png)

If I uninstall bokeh and reinstall with 2.2.2 the output is correct:
![image](https://user-images.githubusercontent.com/43394481/109713029-ba785780-7b6e-11eb-9322-e4944e3104d3.png)

**Comment by Hoxbro** [comment]
This should be fixed by updating to the newly released HoloViews 1.14.2.

**Comment by LoriHarris** [comment]
@Hoxbro Thanks! I created a new environment today and installed using `conda install -c pyviz hvplot`. Is this not best practice then if it doesn't install the correct version of Holoviews? Can you recommend a better alternative that installs it all?  Or do we need to run the that standard install line, plus a command to update holoviews.

**Comment by Hoxbro** [comment]
You properly did everything correct. 
The newest version of HoloViews was only released a couple hours ago.

**Comment by LoriHarris** [comment]
Strange...We've been getting this error for a few days. Thanks for your
help though, I'll give this a try.

**Comment by philippjfr** [comment]
Yes, please upgrade to Panel 0.11.0 and HoloViews 1.14.2 for compatibility with Bokeh 2.3. Sorry for the delay in getting compatible packages out.
