### ISSUE TITLE
Potential bug in hvplot.image

### ISSUE THREAD

**Issue by r4ecology** [holoviz/hvplot#569]
I am trying to understand recent changes in behaviour in how image plots multiple variables from xarray datasets.

In hvplot version 0.5.2 the code below will produce an interactive plot showing the variables air and air2. However, I get an error with more recent versions.

```
import xarray as xr
import hvplot.xarray
ds = xr.tutorial.open_dataset('air_temperature')
ds = ds.assign(air2 = lambda x: x.air)
ds.hvplot.image("lon", "lat", z = ["air","air2"])
```

The error message is below. The arguments to image do not appear to have changed in the recent releases. Is this a bug (maybe an interaction issue with newer versions of holoviews) or do I need to modify the image call above?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-1bb880ed700c> in <module>()
      3 ds = xr.tutorial.open_dataset('air_temperature')
      4 ds = ds.assign(air2 = lambda x: x.air)
----> 5 ds.hvplot.image("lon", "lat", z = ["air","air2"])

/home/robert/miniconda3/envs/testing/lib/python3.6/site-packages/hvplot/plotting/core.py in image(self, x, y, z, colorbar, **kwds)
    625             The HoloViews representation of the plot.
    626         """
--> 627         return self(x, y, z=z, kind='image', colorbar=colorbar, **kwds)
    628 
    629     def rgb(self, x=None, y=None, z=None, bands=None, **kwds):

/home/robert/miniconda3/envs/testing/lib/python3.6/site-packages/hvplot/plotting/core.py in __call__(self, x, y, kind, **kwds)
     77                 return pn.panel(plot, **panel_dict)
     78 
---> 79         return self._get_converter(x, y, kind, **kwds)(kind, x, y)
     80 
     81     def _get_converter(self, x=None, y=None, kind=None, **kwds):

/home/robert/miniconda3/envs/testing/lib/python3.6/site-packages/hvplot/converter.py in __call__(self, kind, x, y)
    997                             el._dataset = ds
    998                             return el
--> 999                         obj = datasets.apply(method, x, y, per_element=True, link_inputs=False)
   1000                     else:
   1001                         obj = HoloMap({(z,)+k: method(x, y, z, dataset[k])

/home/robert/miniconda3/envs/testing/lib/python3.6/site-packages/holoviews/core/accessors.py in pipelined_call(*args, **kwargs)
     35             if not hasattr(inst._obj, '_pipeline'):
     36                 # Wrapped object doesn't support the pipeline property
---> 37                 return __call__(*args, **kwargs)
     38 
     39             inst_pipeline = copy.copy(inst._obj. _pipeline)

TypeError: __call__() got multiple values for argument 'link_inputs'

**Comment by philippjfr** [comment]
Thanks for the bug report but could you try with the latest version (0.7.1) and make sure you also update HoloViews to the latest version?

**Comment by r4ecology** [comment]
Thanks for the quick response. I have just tried it with 0.7.1 and the two most recent versions of holoviews and the same error apears. I think the error is likely caused by a positional argument being picked up by the kwargs and causing two values of link_inputs going through to the call.

**Comment by philippjfr** [comment]
Can confirm, looking into it.

**Comment by r4ecology** [comment]
Thanks. This appears to solve the problem fully.
