### ISSUE TITLE
Can't import hvplot.pandas

### ISSUE THREAD

**Issue by stualden** [holoviz/hvplot#573]
#### Complete, minimal, self-contained example code that reproduces the issue
```
import hvplot.pandas

```
#### Problem description
When I try the import, I get the following response in a Jupyter Notebook on Chrome or Edge:

```
Javascript error adding output!
Error: Cannot find module '@bokehjs/styles/buttons'
See your browser Javascript console for more details.
```

With Internet Explorer, I get the following (both messages):

```
Javascript error adding output!
SyntaxError: Expected ';'
See your browser Javascript console for more details.

Javascript error adding output!
SyntaxError: Syntax error
See your browser Javascript console for more details.
```

After that, any calls to hvplot produce no output. 

#### Console output

```
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:45677 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:45677
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:24190 load_extensions Arguments(4)
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:33602 Loaded moment locale en
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:24167 Loading extension: nbextensions_configurator/config_menu/main
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:24167 Loading extension: contrib_nbextensions_help_item/main
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:24167 Loading extension: execute_time/ExecuteTime
ExecuteTime.js?v=20210311005344:55 [ExecuteTime] patching CodeCell.prototype.get_callbacks
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:24167 Loading extension: jupyter-js-widgets/extension
2main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35558 Ignoring untrusted application/javascript output.
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:27218 HTML Sanitizer script removed Object
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:38824 Session: kernel_created (8cd85549-c81e-404a-a24a-45f79172e6d1)
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:37969 Starting WebSockets: ws://localhost:8888/api/kernels/321c83fb-1f7d-45bf-9d02-d837034df23d
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:37612 Kernel: kernel_connected (321c83fb-1f7d-45bf-9d02-d837034df23d)
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:37612 Kernel: kernel_ready (321c83fb-1f7d-45bf-9d02-d837034df23d)
VM40:305 [bokeh] setting log level to: 'info'
main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35621 Error: Cannot find module '@bokehjs/styles/buttons'
    at require (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:210:27)
    at Object._ (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:1072:153)
    at require (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:228:27)
    at Object._ (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:1033:487)
    at require (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:228:27)
    at Object._ (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:1032:120)
    at require (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:228:27)
    at Object.main.register_plugin (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:268:24)
    at eval (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:1026:26)
    at eval (eval at append_javascript (main.min.js?v=3d694ae0395dfef075eb0c5e8f10a21a8689f66b1e109f0c303b3573fd6512da3aebdc33284fe88676520a882517a504aec0051332d7d513d7c542465fc96b6f:35619), <anonymous>:1031:7)
DevTools failed to load SourceMap: Could not load content for http://localhost:8888/static/notebook/js/main.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
``` 

#### ALL software version info
channels:
  - conda-forge
  - defaults
 
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - bokeh=2.3.0=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2021.1.19=h06a4308_1
  - category_encoders=2.2.2=py_0
  - certifi=2020.12.5=py38h06a4308_0
  - cffi=1.14.5=py38h261ae71_0
  - chardet=4.0.0=py38h06a4308_1003
  - colorcet=2.0.6=pyhd3eb1b0_0
  - conda-package-handling=1.7.2=py38h03888b9_0
  - confuse=1.4.0=pyhd3eb1b0_0
  - cryptography=3.3.1=py38h3c74f83_1
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.67.4=h36276a3_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdbscan=0.8.27=py38h5c078b8_0
  - holoviews=1.14.2=pyhd3eb1b0_0
  - htmlmin=0.1.12=pyhd3eb1b0_1
  - hvplot=0.7.1=pyhd3eb1b0_1
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - imagehash=4.2.0=pyhd3eb1b0_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.21.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.1=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.17.1=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h2828fa1_18
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.2=h20c2e04_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.35.0=py38h612dafd_4
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.4=py38h06a4308_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - missingno=0.4.2=pyhd3eb1b0_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - mlxtend=0.18.0=pyhd3deb0d_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - notebook=6.2.0=py38h06a4308_0
  - numba=0.52.0=py38ha9443f7_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1j=h27cfd23_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.3=py38ha9443f7_0
  - pandas-profiling=2.9.0=pyhd3eb1b0_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - panel=0.10.3=pyhd3eb1b0_0
  - param=1.10.1=pyhd3eb1b0_0
  - parso=0.8.1=pyhd3eb1b0_0
  - patsy=0.5.1=py38_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - phik=0.11.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - psycopg2=2.8.6=py38h3c74f83_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyct=0.4.8=py38_0
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.8=hdb3f193_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pyviz_comms=2.0.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.4.1=py38h27cfd23_1
  - pyzmq=20.0.0=py38h2531618_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.87=py38h7b6447c_1
  - scikit-learn=0.24.1=py38ha9443f7_0
  - scipy=1.6.1=py38h91f5cce_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - soupsieve=2.2=pyhd3eb1b0_0
  - sqlalchemy=1.3.23=py38h27cfd23_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.2=py38h27cfd23_0
  - tangled-up-in-unicode=0.0.7=pyhd3eb1b0_0
  - tbb=2020.3=hfd86e86_0
  - terminado=0.9.2=py38h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - visions=0.5.0=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - wordcloud=1.8.1=py38h25fe258_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - lxml==4.6.2
    - pydotplus==2.0.2
    - python-graphviz==0.16

Thank you!  If this is a bokeh issue rather than an hvplot issue, please advise.

**Comment by Hoxbro** [comment]
Try updating panel to the latest version with this command `conda install panel=0.11 -c pyviz`

**Comment by stualden** [comment]
Thank you!  That eliminated the error message.  Then to get hvplot to actually work, I needed to create fresh notebooks - any existing notebook that had been run with the old panel was "tainted" (it appears to be [this bug](https://github.com/holoviz/holoviews/issues/3617)).

Just one more question (and then I'll get back to work!) - is it best to use the pyviz channel for anything hvplot related, overriding conda defaults where needed?  (For example, in this case, a conda update --all would just move me back to panel 0.10.3.)  Thanks again.

**Comment by Hoxbro** [comment]
Good to hear that it worked. 

I use the pyviz channel for all the pyviz packages , e.g. `panel`, `holoviews`, etc.  I have the following setup for my `.condarc` file.
``` yaml
ssl_verify: true
channels:
  - pyviz
  - conda-forge
  - defaults
```

**Comment by stualden** [comment]
Thank you, I will try that channel priority.

Should I re-report the `IPKernelApp No such comm: hv-extension-comm` bug?  Looks like that ticket was closed back in April 2019, but the bug appears to still be there (I just triggered it a different way, that's all).

**Comment by jbednar** [comment]
Yes, that's the channel priority I'd use; pyviz is always either equal to or more up to date than conda-forge or defaults.

The "No such comm" warnings are meaningless but very irritating. I've offered $500 USD to anyone who can safely eliminate them, but so far no takers.

**Comment by stualden** [comment]
Once I'm up to speed on all this, I may just take on your offer :-)

It's not so  much the warning that bothers me, it's the accompanying fact that after a notebook has experienced an error like the one I described above, calls to `hvplot` don't generate any output in the notebook (and instead just generate those annoying warnings in the console).  

Restarting the kernel or reloading the notebook doesn't fix it, even with (in my case) an updated `panel`.  You have to copy your code to a brand new notebook and run that.  That's the bug (at least it seems like a bug) I'd like to report, but I guess I'm not sure **where** to report it.

**Comment by philippjfr** [comment]
@stualden I suspect that's weird incompatible versions sticking around. The procedure to fix that is usually:

1. Clear the notebook
2. Save
3. (If in JupyterLab repeat for all open JLab tabs)
4. Reload the page

I'm still working out an approach that would resolve this properly.

**Comment by jbednar** [comment]
And in any case the "No such comm" messages are generally unrelated to the actual problem; people see them whenever they are experiencing a problem and thus think they are relevant, but they also occur when there is no problem, so they are really just a distraction!

**Comment by stualden** [comment]
Thank you everyone - I'm grateful for your help, and once again a happy hvplot user.
