### ISSUE TITLE
Comma separated digits formatting.

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/hvplot#578]
I'm trying to get comma separated digits for pretty yticks for large numbers. 

I tried both of the following as per python documentation on printf
```
yformatter="{:,}"
yformatter="%'d"
```

but neither give the desired output.

To be clear, I would like 3e7 to render as 30,000,000.

Thank you.

**Comment by brl0** [comment]
I was looking to do the same thing today and found [this](https://discourse.holoviz.org/t/how-do-i-format-yaxis-tick-labels-with-comma-as-thousands-seperator/1774) on the holoviz discourse, thanks to @MarcSkovMadsen.

```python
from bokeh.models.formatters import NumeralTickFormatter

formatter = NumeralTickFormatter(format="0,0")

plot.opts(yformatter=formatter)
```

**Comment by LinuxIsCool** [comment]
Thanks to both of you!
