### ISSUE TITLE
On a plot of a streamz dataframe, don't plot "example"

### ISSUE THREAD

**Issue by martindurant** [holoviz/hvplot#592]
When plotting streamz dataframes, the "example" point is always plotted, even though it doesn't normally contain valid data.

**Comment by martindurant** [comment]
Since I believe the point is useful for setting up the plot, when the first point arrives, that example point can be replaced.

**Comment by philippjfr** [comment]
Good point, really we just need the dtypes, index and column names so the simplest fix is just to do an `.iloc[:0]` on the example data.
