### ISSUE TITLE
widgets are unresponsive in almost all of the reference guide

### ISSUE THREAD

**Issue by daliagachc** [holoviz/hvplot#598]
guide->gallery 

for example—but have found many more places—: 
https://hvplot.holoviz.org/user_guide/Widgets.html

**Comment by jbednar** [comment]
It looks like hvPlot has never been rebuilt with the warnings that you can see all over the rest of the HoloViz tools, e.g. http://holoviews.org/user_guide/Live_Data.html (see box on the right).  @jlstevens ?

**Comment by daliagachc** [comment]
thank you!  I wanted to add 2 points since i think the problem goes deeper in my case: 
- in the provided link all of the widgets work (http://holoviews.org/user_guide/Live_Data.html)
- interaction seems to be broken (at least in my case) even when running locally.
for example, when i run the following example (provided here :https://hvplot.holoviz.org/user_guide/Geographic_Data.html)
i get the exact same results as in the mentioned link: no interaction at all
```python
air_ds = xr.tutorial.open_dataset('air_temperature').load()

air_ds.hvplot.quadmesh(
    'lon', 'lat', 'air', projection=ccrs.Orthographic(-90, 30),
    global_extent=True, frame_height=540, cmap='viridis',
    coastline=True
)
```

**Comment by jlstevens** [comment]
If the doc build is not pinning nbsite, it should be adding the warning. I'll double check that it is correctly configured to warn otherwise.

**Comment by jlstevens** [comment]
I'm not sure when exactly, but the page has been rebuilt and the interactivity warning is showing:

![image](https://user-images.githubusercontent.com/890576/121895848-48bfb600-cce6-11eb-82cf-3d0cbe7deaef.png)

(and the same for Live Data).

> interaction seems to be broken (at least in my case) even when running locally.

```python
air_ds.hvplot.quadmesh(
    'lon', 'lat', 'air', projection=ccrs.Orthographic(-90, 30),
    global_extent=True, frame_height=540, cmap='viridis',
    coastline=True
)
```

Could you check if this is still true with the latest releases of hvplot and holoviews? If so, please report that in a new issue: I'm going to close this one as everything else here issue concerns the website which is now fixed.
