### ISSUE TITLE
size and s not working as argument to scatter

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#608]
holoviews: 1.14.3
hvplot: 0.7.1

As hvplot is a drop in replacement for the pandas Dataframe `.plot` method I would expect the `s` argument for size to be supported. C.f. 

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.scatter.html

![image](https://user-images.githubusercontent.com/42288570/118384030-590b4500-b603-11eb-8880-0f49abe46dc9.png)

But it does not change the size of the markers

```python
import holoviews as hv
import hvplot.pandas
import panel as pn
from bokeh.sampledata.iris import flowers

pn.extension(sizing_mode="stretch_width")
hv.extension("bokeh")

iris_dataset = flowers
accent_color = "#ff286e"

scatter = iris_dataset.hvplot.scatter(
    x="sepal_length", y="sepal_width", c=accent_color, s=10)
pn.panel(scatter).servable()
```

![image](https://user-images.githubusercontent.com/42288570/118384070-9243b500-b603-11eb-8096-33e41eea0a89.png)

##  `size` argument does not work either

```python
import holoviews as hv
import hvplot.pandas
import panel as pn
from bokeh.sampledata.iris import flowers

pn.extension(sizing_mode="stretch_width")
hv.extension("bokeh")

iris_dataset = flowers
accent_color = "#ff286e"

scatter = iris_dataset.hvplot.scatter(
    x="sepal_length", y="sepal_width", c=accent_color, size=10)
pn.panel(scatter).servable()
```

![image](https://user-images.githubusercontent.com/42288570/118384082-abe4fc80-b603-11eb-9322-5c016ce2eddd.png)

## `s .opt` argument does not work either

```python
import holoviews as hv
import hvplot.pandas
import panel as pn
from bokeh.sampledata.iris import flowers

pn.extension(sizing_mode="stretch_width")
hv.extension("bokeh")

iris_dataset = flowers
accent_color = "#ff286e"

scatter = iris_dataset.hvplot.scatter(
    x="sepal_length", y="sepal_width", c=accent_color).opts(s=10)
pn.panel(scatter).servable()
```

![image](https://user-images.githubusercontent.com/42288570/118384140-0716ef00-b604-11eb-878d-deaaed2e18c5.png)

## `size .opts` argument works

```python
import holoviews as hv
import hvplot.pandas
import panel as pn
from bokeh.sampledata.iris import flowers

pn.extension(sizing_mode="stretch_width")
hv.extension("bokeh")

iris_dataset = flowers
accent_color = "#ff286e"

scatter = iris_dataset.hvplot.scatter(
    x="sepal_length", y="sepal_width", c=accent_color).opts(size=10)
pn.panel(scatter).servable()
```

![image](https://user-images.githubusercontent.com/42288570/118384119-e0f14f00-b603-11eb-9531-ffbdb20f2ae4.png)

**Comment by MarcSkovMadsen** [comment]
For the Matplot backend the `s .opts` argument works according to the [Reference](http://holoviews.org/reference/elements/matplotlib/Scatter.html). 

It's simply confusing that `s .opts` works for Matplotlib and `size .opts` works for Bokeh backend. This leads to mental overhead.

**Comment by philippjfr** [comment]
I can't reproduce any of the issues you reported about `s` and `size` in hvPlot, both are working for me. The style option naming across backends in HoloViews is a separate discussion.

**Comment by jbednar** [comment]
The `s` argument works fine for me using the first code snippet above  with hv=1.14.3, hvplot=0.7.2a1, and bokeh=2.3.1.  Making .opts accept the same options (name and semantics) between different backends in general is a huge job and seems unlikely without some major grant funding.
