### ISSUE TITLE
Control resolution of rasterized plots

### ISSUE THREAD

**Issue by tom-andersson** [holoviz/hvplot#626]
I'm using `ds.hvplot.quadmesh` to project and visualise a heatmap of geospatial data. Due to the size of the data, I have to set `rasterize=True`. As far as I'm aware (and I may be wrong), the only way to control the spatial resolution of the rasterization process is to specify the `height` and `width` parameters in the arguments to the plotting function. This has the undesirable effect of making all the figure element (labels, bokeh widgets, etc) super small. It would be preferable if there were a way to control the downsampling process without changing the actual size of the plot. Is there something I'm missing or am I on to something? Cheers!

**Comment by tom-andersson** [comment]
Hmm, this is a bit of a dilemma. 3 would save people time on searching through HoloViews documentation while adding some nice additional functionality (e.g. reducing resolution to send a plot over email, etc). Having to manually set the height and width of the underlying raster (e.g. through option 2 or 1) is a bit unintuitive for new users. The extra flexibility afforded by 1 would be useful too, though.

3 would get my main vote, but 1 would be a nice plus (with a link to the appropriate HoloViews documentation). I guess you would have to ensure users didn't supply both `rasterize_factor` and `rasterize_args={'height': ..., 'width': ...` at the same time though.

**Comment by jbednar** [comment]
@philippjfr , any votes or comments?

**Comment by philippjfr** [comment]
I'd be quite happy to add option 1 and 3, that said I'm hoping we can find a better name for both.

**Comment by itsgifnotjiff** [comment]
I run into this daily and I am not sure how to keep the rerasterization on zoom/pan of simply setting `rasterize=True` while avoiding the "half the dataset disappears" bug. Mr. @tom-andersson did you ever get it to work fully and not just for a static image sir?

**Comment by Hoxbro** [comment]
I see no problem in having better support for different geo-projection and datashading. 

Though, I don't think this will be added in the near future.

**Comment by philipc2** [comment]
@jbednar @itsgifnotjiff 

Wondering if there's any follow up on this issue. I receive the following when I try to set a `pixel_ratio` using `hvPlot`

``WARNING:param.main: pixel_ratio option not found for polygons plot with bokeh; similar options include: []``

**Comment by ahuang11** [comment]
I don't think we ported pixel_ratio over to hvplot yet; workaround is to simply call rasterize outside of hvplot `rasterize(ds.hvplot(...), pixel_ratio=...)` (but I haven't tested)

Would you be interested in contributing it? It should be fairly straightforward; just propagating the kwarg like how `cticks` was added in this PR https://github.com/holoviz/hvplot/pull/1368/files. Then call it in https://github.com/holoviz/hvplot/blob/main/hvplot/converter.py#L1795

**Comment by philipc2** [comment]
> I don't think we ported pixel_ratio over to hvplot yet; workaround is to simply call rasterize outside of hvplot `rasterize(ds.hvplot(...), pixel_ratio=...)` (but I haven't tested)
> 
> Would you be interested in contributing it? It should be fairly straightforward; just propagating the kwarg like how `cticks` was added in this PR https://github.com/holoviz/hvplot/pull/1368/files. Then call it in https://github.com/holoviz/hvplot/blob/main/hvplot/converter.py#L1795

I would be interested! We utilize the `pixel_ratio` parameter quite extensively for the [UXarray ](https://github.com/UXARRAY/uxarray) project.

I'll open up a PR for this.

**Comment by itsgifnotjiff** [comment]
I am currently on leave and I will test, open a new issue and report back ASAP. Sorry for the delay.
