### ISSUE TITLE
ImportError: cannot import name 'Nullable' from 'bokeh.core.properties' (C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\properties.py)

### ISSUE THREAD

**Issue by charuka-dissanayaka** [holoviz/hvplot#629]
above the error pop up when importing the holoviews.I try different methods but didn't work. The following import
 import plotly.express as px
        from wordcloud import WordCloud,STOPWORDS
        import holoviews as hv
        from holoviews import opts
        hv.extension('bokeh')
        
        And installed the bokeh using pip install bokeh
produces an error:
      I update the pip also
       ImportError: cannot import name 'Nullable' from 'bokeh.core.properties' (C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\properti`enter code here`es.py)

        how can I fix this error?

**Comment by philippjfr** [comment]
Hi, @charuka-dissanayaka, thanks for your issue, you should update to a more recent version of Bokeh (ideally Bokeh 2.3.2).

**Comment by iamsuperdev** [comment]
cannot import name 'InstanceDefault' from 'bokeh.core.properties'

**Comment by maximlt** [comment]
What versions of Bokeh have you installed @iamsuperdev ? In general, it's recommended to provide a comprehensive description of your problem, your message is a little terse, there isn't much we can do to help you at this stage.

**Comment by iamsuperdev** [comment]
ModuleNotFoundError: No module named 'bokeh.core.serialization'

**Comment by maximlt** [comment]
Please provide a complete example for us to try to reproduce this error, along with your full list of dependencies.

**Comment by iamsuperdev** [comment]
I installed conda environment by using anaconda.
But this project has error.
ModuleNotFoundError: No module named 'bokeh.core.serialization'
please check

**Comment by maximlt** [comment]
Please provide the code you are trying to run and provide the output of running the `conda info` and `conda list` commands.

**Comment by iamsuperdev** [comment]
https://huggingface.co/spaces/sophiamyang/Panel_PDF_QA/blob/main/LangChain_QA_Panel_App.ipynb

**Comment by iamsuperdev** [comment]
active environment : Panel_PDF_QA
    active env location : C:\Users\Root\anaconda3\envs\Panel_PDF_QA
            shell level : 1
       user config file : C:\Users\Root\.condarc
 populated config files : C:\Users\Root\.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\Root\anaconda3  (writable)
      conda av data dir : C:\Users\Root\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Root\anaconda3\pkgs
                          C:\Users\Root\.conda\pkgs
                          C:\Users\Root\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Root\anaconda3\envs
                          C:\Users\Root\.conda\envs
                          C:\Users\Root\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9
Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

**Comment by iamsuperdev** [comment]
# Name                    Version                   Build  Channel
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0
backoff                   2.2.1                    pypi_0    pypi
blas                      1.0                         mkl
bleach                    6.0.0                    pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.5           py310h9128911_0
bzip2                     1.0.8                he774522_0
ca-certificates           2022.12.7            h5b45459_0    conda-forge
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
chromadb                  0.3.21                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
clickhouse-connect        0.5.22                   pypi_0    pypi
colorama                  0.4.6           py310haa95532_0
contourpy                 1.0.7                    pypi_0    pypi
dataclasses-json          0.5.7                    pypi_0    pypi
debugpy                   1.5.1           py310hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
duckdb                    0.7.1                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0
fastapi                   0.95.1                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
gpt-index                 0.4.24                   pypi_0    pypi
greenlet                  2.0.2                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hnswlib                   0.7.0           py310h220cb41_0    conda-forge
httptools                 0.5.0                    pypi_0    pypi
huggingface-hub           0.14.1                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.15.0             pyh025b116_0    conda-forge
ipython                   8.12.0          py310haa95532_0
ipywidgets                8.0.6                    pypi_0    pypi
jedi                      0.18.1          py310haa95532_1
jinja2                    3.1.2           py310haa95532_0
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
jupyter-bokeh             3.0.7                    pypi_0    pypi
jupyter_client            8.1.0           py310haa95532_0
jupyter_core              5.3.0           py310haa95532_0
jupyterlab-widgets        3.0.7                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
langchain                 0.0.154                  pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libdeflate                1.17                 h2bbff1b_0
libffi                    3.4.2                hd77b12b_6
libpng                    1.6.39               h8cc25b3_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.5.0                h6c2663c_2
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
lz4                       4.3.2                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
marshmallow               3.19.0                   pypi_0    pypi
marshmallow-enum          1.5.1                    pypi_0    pypi
matplotlib-inline         0.1.6           py310haa95532_0
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0           py310h2bbff1b_0
mkl_fft                   1.3.1           py310ha0764ea_0
mkl_random                1.2.2           py310h4ed8f06_0
monotonic                 1.6                      pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nest-asyncio              1.5.6           py310haa95532_0
networkx                  3.1                      pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numexpr                   2.8.4           py310hd213c9f_0
numpy                     1.24.3          py310hdc03b94_0
numpy-base                1.24.3          py310h3caf3d7_0
openai                    0.27.5                   pypi_0    pypi
openapi-schema-pydantic   1.2.4                    pypi_0    pypi
openssl                   1.1.1t               hcfcfb64_0    conda-forge
orjson                    3.8.11                   pypi_0    pypi
packaging                 23.0            py310haa95532_0
pandas                    2.0.1                    pypi_0    pypi
panel                     0.14.4                   pypi_0    pypi
param                     1.13.0                   pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1          py310haa95532_0
platformdirs              2.5.2           py310haa95532_0
posthog                   3.0.1                    pypi_0    pypi
prompt-toolkit            3.0.36          py310haa95532_0
psutil                    5.9.0           py310h2bbff1b_0
pure_eval                 0.2.2              pyhd3eb1b0_0
pycryptodome              3.17                     pypi_0    pypi
pyct                      0.5.0                    pypi_0    pypi
pydantic                  1.10.7                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0
pyparsing                 3.0.9                    pypi_0    pypi
pypdf                     3.8.1                    pypi_0    pypi
pypdf2                    3.0.1                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.10.11              h966fe2a_2
python-dateutil           2.8.2              pyhd3eb1b0_0
python-dotenv             1.0.0                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytz                      2023.3                   pypi_0    pypi
pyviz-comms               2.2.1                    pypi_0    pypi
pywin32                   305             py310h2bbff1b_0
pyyaml                    6.0             py310h2bbff1b_1
pyzmq                     25.0.2          py310hd77b12b_0
regex                     2023.3.23                pypi_0    pypi
requests                  2.29.0                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentence-transformers     2.2.2                    pypi_0    pypi
sentencepiece             0.1.98                   pypi_0    pypi
setuptools                66.0.0          py310haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0                    pypi_0    pypi
sqlalchemy                2.0.12                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
starlette                 0.26.1                   pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tiktoken                  0.3.3                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.0                    pypi_0    pypi
torchvision               0.15.1                   pypi_0    pypi
tornado                   6.2             py310h2bbff1b_0
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.7.1           py310haa95532_0
transformers              4.28.1                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
typing-inspect            0.8.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
ucrt                      10.0.20348.0         haa95532_0
urllib3                   1.26.15                  pypi_0    pypi
uvicorn                   0.22.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.34.31931         h4c5c07a_11    conda-forge
watchfiles                0.19.0                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    pypi_0    pypi
websockets                11.0.2                   pypi_0    pypi
wheel                     0.38.4          py310haa95532_0
widgetsnbextension        4.0.7                    pypi_0    pypi
xyzservices               2023.2.0                 pypi_0    pypi
xz                        5.2.10               h8cc25b3_1
yaml                      0.2.5                he774522_0
yarl                      1.9.2                    pypi_0    pypi
zeromq                    4.3.4                hd77b12b_0
zlib                      1.2.13               h8cc25b3_0
zstandard                 0.21.0                   pypi_0    pypi
zstd                      1.5.5                hd43e919_0

**Comment by iamsuperdev** [comment]
please let me know within a hour.
Thank you for your support.
Looking forward to your reply.
Best regards.

**Comment by maximlt** [comment]
hvPlot is not installed in the environment you shared, the issue you report does not have anything to do with it. I suggest you create a completely new environment, install the dependencies you need, and try again running the code.

> please let me know within a hour.

You cannot really ask that to maintainers of Open Source Software, they are not your regular kind of support as they usually work for free.
