### ISSUE TITLE
Add bgcolor argument

### ISSUE THREAD

**Issue by jbednar** [holoviz/hvplot#636]
As far as I can tell, the Pandas .plot() API does not have a way to [change the background color](https://stackoverflow.com/questions/23123272/change-pandas-plot-background-color) without dropping down to matplotlib. hvPlot appears to inherit this the same limitation. We can of course do `.opts(bgcolor='black')`, but I've found that in many examples that's the only use of .opts I have to resort to, and without it I wouldn't need to explain .opts.  Can we have a `bgcolor=` argument to cover this case?

**Comment by maximlt** [comment]
Implemented in https://github.com/holoviz/hvplot/pull/1308
