### ISSUE TITLE
df.interactive() fails on a pandas DataFrame that has 'interface' in df.columns

### ISSUE THREAD

**Issue by geronimos** [holoviz/hvplot#645]
#### ALL software version info
- holoviz_tutorial (see: https://pyviz-dev.github.io/holoviz/tutorial/Setup.html) on Windows 10

#### Description of expected behavior and the observed behavior
*Expected*: executing ``interactive()`` on a ``pandas.DataFrame`` should return an interactive pandas DataFrame that I can use with widgets. This should be true for any column name specified in the ``DataFrame``.

*Observed*: ``interactive()`` fails on a ``pandas.DataFrame`` object that includes a column named ``interface``.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import hvplot.pandas
pd.DataFrame([1,2,3], columns=['interface']).interactive()

```

#### Stack traceback and/or browser JavaScript console output
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-dff52aeb506d> in <module>
      1 import hvplot.pandas
----> 2 pd.DataFrame([1,2,3], columns=['interface']).interactive()

~\Projects\holoviz_tutorial\envs\default\lib\site-packages\hvplot\pandas.py in <lambda>(self)
     17     setattr(pd.Series, name, plot_prop)
     18 
---> 19     _patch_interactive = lambda self: Interactive(self)
     20     _patch_interactive.__doc__ = Interactive.__call__.__doc__
     21     interactive_prop = property(_patch_interactive)

~\Projects\holoviz_tutorial\envs\default\lib\site-packages\hvplot\interactive.py in __init__(self, obj, transform, plot, depth, loc, center, dmap, inherit_kwargs, max_rows, **kwargs)
     83         self._max_rows = max_rows
     84         self._kwargs = kwargs
---> 85         ds = hv.Dataset(self._obj)
     86         self._current = self._transform.apply(ds, keep_index=True, compute=False)
     87         self._init = True

~\Projects\holoviz_tutorial\envs\default\lib\site-packages\holoviews\core\data\__init__.py in __init__(self, data, kdims, vdims, **kwargs)
    339 
    340         validate_vdims = kwargs.pop('_validate_vdims', True)
--> 341         initialized = Interface.initialize(type(self), data, kdims, vdims,
    342                                            datatype=kwargs.get('datatype'))
    343         (data, self.interface, dims, extra_kws) = initialized

~\Projects\holoviz_tutorial\envs\default\lib\site-packages\holoviews\core\data\interface.py in initialize(cls, eltype, data, kdims, vdims, datatype)
    206 
    207         # Process Element data
--> 208         if (hasattr(data, 'interface') and issubclass(data.interface, Interface)):
    209             if datatype is None:
    210                 datatype = [dt for dt in data.datatype if dt in eltype.datatype]

TypeError: issubclass() arg 1 must be a class
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/29955288/127132581-2e1ee4ae-b416-426c-8654-878f42ed5889.png)

**Comment by jbednar** [comment]
Thanks for the report! Seems like we should first be checking if data.interface is a class, and only call issubclass on it if it is. Would you be up for making such a change to hvplot?  If not, I think we'll be able to take care of it...

**Comment by geronimos** [comment]
Sure, I can implement this in a new branch and create a pull request. Are there any special contribution guidelines?

**Comment by jbednar** [comment]
Great! The only guidelines here would be to make sure it's a clean diff (no extraneous whitespace changes, etc.) and to add a test for this case if possible (or we can do that if the tests are daunting). The test case would need to fail right now but pass after the fix!

**Comment by geronimos** [comment]
I implemented a fix in ``holoviews/core/data/interface`` and also added a test that succeeds only after the fix. However, I do not have access rights to push the created ``fix-core-data-interface`` branch to holoviews. How can I add the fix to origin?

**Comment by jbednar** [comment]
Great! Please open a PR with those changes: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
