### ISSUE TITLE
Using quadmesh with interactive

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/hvplot#646]
`AttributeError: 'function' object has no attribute 'quadmesh'`

```
ds.air.interactive.hvplot.quadmesh()
```

**Comment by jbednar** [comment]
Hmm; none of the accessors seem to work with xarray .interactive (.scatter, .points, etc.). Reproducer:

```
import xarray as xr, hvplot.xarray
ds = xr.tutorial.open_dataset('air_temperature').load()
ds.air.interactive.hvplot.points
```

**Comment by itsgifnotjiff** [comment]
Same here using 
```python
xdsi = xds.QQ.interactive.sel(**sel_dict)
xdsi.hvplot.quadmesh()
```
where `xds` is an `xarray.DataSet` and `sel_dict` is a valid and working set of widgets.

**Comment by Hoxbro** [comment]
This should be fixed with https://github.com/holoviz/hvplot/pull/781

Until then you should be able to do something like `xdsi.hvplot(..., kind='quadmesh')`
