### ISSUE TITLE
Cannot show colorbar on scattter plot with datashading

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#649]
hvplot: 0.7.3

I'm trying to get the colorbar displayed on a scatter plot with datashading. But cannot.

![image](https://user-images.githubusercontent.com/42288570/128620974-02b5f412-cf2e-422d-89a0-e42bd0c2d156.png)

```python
import hvplot.xarray  # noqa
import panel as pn
import xarray as xr

pn.extension(sizing_mode="stretch_width")

air_ds=xr.tutorial.open_dataset("air_temperature").load()
air = air_ds.air
plot = (
    air.hvplot.scatter("time", groupby=[], datashade=True, responsive=True, cmap="YlOrBr", colorbar=True)
    # * air.mean(["lat", "lon"]).hvplot.line("time", color=accent_base_color, responsive=True)
)
pn.pane.HoloViews(
    plot, min_height=400, sizing_mode="stretch_both"
).servable()
```

## Additional Context

- Basti is reporting the same problem here https://discourse.holoviz.org/t/hvplot-scatter-plot-no-colorbar/1890
- As far as I remember "you" had problems in the Scipy 2021 Tutorial as well.

**Comment by jbednar** [comment]
Colorbars are only available for `rasterize=True`; if you use `datashade=True`, datashader is in charge of the final shading step (converting to RGB), and so no information about shading is available to Bokeh for when it needs to compute a colorbar. Use `rasterize=True` whenever possible, to avoid this problem!
