### ISSUE TITLE
Like matplotlib syntax, allow specifying marker on line plots

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#650]
Rather than type twice the same:
df.hvplot("lon", "lat") * df.hvplot.scatter("lon", "lat")

Would be nice for exploratory usage (similar to tiles, coastline, etc)
df.hvplot("lon", "lat", marker="o")

**Comment by jbednar** [comment]
Completely agree, but that's already an open issue: https://github.com/holoviz/hvplot/issues/168

Contributions welcome!
