### ISSUE TITLE
move scalar coords to title in hvplot.xarray

### ISSUE THREAD

**Issue by raybellwaves** [holoviz/hvplot#656]
#### Is your feature request related to a problem? Please describe.
Upstreaming xarray .plot() methods to hvplot.xarray

#### Describe the solution you'd like
an xarray.Dataset with one data variable:
`ds["data_var"].plot()`
to match
`ds,hvplot()`

#### Additional context
```
import xarray as xr
import hvplot.xarray

ds = xr.tutorial.open_dataset("air_temperature").isel(lat=0, lon=0)
ds["air"].plot()
```

<img width="425" alt="Screen Shot 2021-09-06 at 10 40 38 PM" src="https://user-images.githubusercontent.com/17162724/132275954-827286c0-81c9-4cd1-943a-cfe6f393905e.png">

```
ds.hvplot()
```
<img width="721" alt="Screen Shot 2021-09-06 at 10 41 41 PM" src="https://user-images.githubusercontent.com/17162724/132276030-07e2cd2a-8019-4079-bfab-78a1ead377de.png">

**Comment by maximlt** [comment]
Hi @raybellwaves!

Thanks for raising this, hvplot would indeed benefit from being more coherent here with the output obtained from xarray's plot API. I'll address it soon.
