### ISSUE TITLE
Tests failing on Python 3.7 due to CRS interpretation

### ISSUE THREAD

**Issue by maximlt** [holoviz/hvplot#657]
The tests are currently failing on Python 3.7 because of the test `test_plot_with_crs_as_nonexistent_attr_str` that expects an error to be raised when a wrong CRS (`'foo'`) value is passed to an image plot.

`pyproj` doesn't seem to be bothered by interpreting `'foo'` as a correct CRS (or at least it doesn't raise an error). I've tried it with the version installed in the dev environment (2.6.1post1, *defaults* is lagging on pyproj releases) and with the latest version, it never raises an error and actually returns:
```
<Geographic 2D CRS: EPSG:4289>
Name: Amersfoort
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: Netherlands - onshore, including Waddenzee, Dutch Wadden Islands and 12-mile offshore coastal zone.
- bounds: (3.2, 50.75, 7.22, 53.7)
Datum: Amersfoort
- Ellipsoid: Bessel 1841
- Prime Meridian: Greenwich
```

The utility function that checks the CRS validity in hvplot seems to have been borrowed from `salem` where it has been updated. I've tried validating `'foo'` with salem`s updated utility function and again, it was interpreted as correct.

I've got no clue why `'foo'` is a valid CRS for pyproj (now, since it must have failed in the past for the test suite to pass). Fixing the test though is not so hard, for instance`pyproj.Proj('wrong')` raises an error, even if that's just a work around to get the test suite to pass...

**Comment by jbednar** [comment]
Sounds like it's now pattern matching "foo" with "Amers _foo_ rt", in which case "foo" should be changed to something that genuinely will not match any projection, such as "name_of_some_invalid_projection".

**Comment by maximlt** [comment]
Yes right I had figured that out too shortly after posting this issue. You can try `projinfo foo` (a PROJ utility) to see that it indeed returns a projection. Either PROJ has changed over time, or this projection has been added to their database. Either way, the PR should fix this issue.
