### ISSUE TITLE
Allow testing without network connection

### ISSUE THREAD

**Issue by mcepl** [holoviz/hvplot#662]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

[Complete build log](https://github.com/holoviz/hvplot/files/7217274/_log.txt) with all packages versions and steps taken (the package is build for both Python 3.8 and Python 3.9). Specifically, hvplot is version 0.7.2. The build is part of the packaging effort on Linux (specifically openSUSE/Factory as of 2021-09-23).

#### Description of expected behavior and the observed behavior
When running the test suite, it fails, because inside of the building environment there is no network connection for security reasons (it is the same with all Linux and non-Linux distribution build systems).

This [patch](https://github.com/holoviz/hvplot/files/7217516/no-network.patch.txt) makes it possible to preload cache (per default in `~/.cache\/xarray_tutorial_data/`) for tests and make it possible to run tests without network.

**Comment by bnavigator** [comment]
Why don't you keep using the  XDG_CACHE_HOME variable? No need to patch anything
https://www.fatiando.org/pooch/latest/api/generated/pooch.os_cache.html#pooch.os_cache

**Comment by mcepl** [comment]
> Why don't you keep using the XDG_CACHE_HOME variable? No need to patch anything
> https://www.fatiando.org/pooch/latest/api/generated/pooch.os_cache.html#pooch.os_cache

I guess, it can go either way.

**Comment by MridulS** [comment]
I'll go ahead and close this, please let us know if the `XDG_CACHE_HOME` fix isn't working.
