### ISSUE TITLE
The `c` parameter of a scatter plot should respect the field name even if it's a color name

### ISSUE THREAD

**Issue by maximlt** [holoviz/hvplot#675]
The parameter `c` of a scatter plot allows to set a field that's used to color the points. The example below shows that when the value passed to `c` is a color (accepted by the backend?) then this color takes precedence over the field name. The example also shows how pandas behaves, i.e. it respects the field name even if it's a color (in the sense of Matplotlib).

![image](https://user-images.githubusercontent.com/35924738/140559992-a501471b-3be0-4416-95ad-f3a8c40d42e7.png)

**Comment by jlstevens** [comment]
@philippjfr Given this is mentioned in the context of the matplotlib transformers, I'm leaving it on the 0.8 milestone.

**Comment by jbednar** [comment]
I agree; a user is likely to know the columns of their own dataset more than the names of all possible named colors, and so if the user provides a value that matches both, I'd bet that the user meant the column name.

**Comment by philippjfr** [comment]
Agreed, hvplot needs to wrap colors which match a dimension should be swapped for `hv.dim(name)` then but we should also making this change in holoviews.

**Comment by maximlt** [comment]
Fixed by https://github.com/holoviz/hvplot/pull/717
