### ISSUE TITLE
Add support for plotting errorbars

### ISSUE THREAD

**Issue by philippjfr** [holoviz/hvplot#7]
Currently no errorbars are supported, it should be possible to add them for Curve, Area, Bars, Scatter

**Comment by wookayin** [comment]
This would be super useful. For someone who come across this issue by Googling, the following reference page discuss how to draw confidence intervals / error bars / spread of values (somewhat manually) using holoviz. Hope it can be useful for future references.

https://hvplot.holoviz.org/user_guide/Plotting.html

```python
delay_min_max = flights.groupby(['day', 'carrier'])['carrier_delay'].mean().groupby('day').agg([np.min, np.max])
delay_mean = flights.groupby('day')['carrier_delay'].mean()

delay_min_max.hvplot.area(x='day', y='amin', y2='amax', alpha=0.2) * delay_mean.hvplot()
```

**Comment by tonyfast** [comment]
#197 closes this
