### ISSUE TITLE
Improve handling of arraylike as input for hvplot

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/hvplot#713]
#### ALL software version info
``` 
pandas    1.3.5
hvplot    0.8.0a11.post9+gfbcc04e
```

#### Description of expected behavior and the observed behavior
When passing an array type like `df.columns` into `hvplot` it raises `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. 

I think there is two solution for this problem; 
* one is either to support array-like formats like `numpy` or `pandas` as input for `hvplot`, 
* the other options is to raise a better error message when passing in a array-like type. 

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import pandas as pd
import hvplot.pandas

df = pd._testing.makeDataFrame()
df.hvplot(y=df.columns)  # Raises ValueError
df.hvplot(y=list(df.columns))  # Works fine
```

**Comment by jbednar** [comment]
I'd vote for automatically converting array-like formats into lists where appropriate.
