### ISSUE TITLE
Accessor support on .hvplot.interactive and hvplot.bind?

### ISSUE THREAD

**Issue by jbednar** [holoviz/hvplot#737]
Using hvplot=0.8.0a16 with the [hvplot.bind](https://github.com/holoviz/hvplot/pull/720) support, I can't quite get my head around it:

```python
import panel as pn, hvplot.pandas, holoviews as hv, pandas as pd, colorcet as cc
df = pd.DataFrame(dict(x=[3E6,2E6,1E6], y=[2E6,1E6,3E6], val=[7,8,9]))

def filter_by_value(val):
    return df[df.val==val]

value = pn.widgets.Select(options=df.val.value_counts().index.tolist(), name='Value')

dfi = hvplot.bind(filter_by_value, val=value).interactive()
dfi.hvplot.scatter('x','y')
```
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1695496/162809192-d058af3c-1c95-4fb7-bc21-3154f8dcff3f.png">

I.e., it works with `kind='scatter'`, but not `.hvplot.scatter`? Similarly, it works with `hvplot.bind(...).interactive()....` but not `hvplot.bind(...).interactive....` (giving `AttributeError: 'function' object has no attribute 'hvplot' ` when I remove the `()` on `.interactive`)? I may just be making myself confused, though.

**Comment by philippjfr** [comment]
I don't think this has anything to with .bind I think this is a general problem with interactive still.

**Comment by jbednar** [comment]
I think the `.interactive` vs `.interactive()` issue is specific to `hvplot.bind` but `.hvplot.scatter()` vs. `.hvplot(..., scatter=...)` is not?

**Comment by tomascsantos** [comment]
> I think the `.interactive.` vs `.interactive().` issue is specific to `hvplot.bind` but `.hvplot.scatter()` vs. `.hvplot(..., scatter=...)` is not?

good workaround for now, thanks!

**Comment by jbednar** [comment]
This hit me again today; not supporting .scatter, .box, etc. makes it very confusing to move an existing pipeline to use .interactive.
