### ISSUE TITLE
Interactivity error with datashade=True option, image moving opposite to cursor displacement

### ISSUE THREAD

**Issue by hxawax** [holoviz/hvplot#739]
Hello, 
I'm reporting a bug on the interactive side of hvplot with the option `datashade=True`.

#### ALL software version info
hvplot version : 0.7.3
xarray version 2022.3.0
datashader version 0.13.0
bokeh version 2.4.2

#### Description of expected behavior and the observed behavior
The expected behavior is to zoom in and out in an image at the cursor location, move the image according to the cursor movement.
The expected behavior is to box zoom at the location of your box. 
The observed behavior is to move image in the opposite direction of cursor movement, box zoom out of the expected box.

#### Complete, minimal, self-contained example code that reproduces the issue
Viewing a heavy image using 'datashade=True' option, the interactivity feels broken. 

`xr.open_dataset('bug2.nc').band_data.hvplot(datashade=True,)`

https://user-images.githubusercontent.com/103639054/163391282-7304b091-a71b-43c2-ae0e-61a5a4d6e8f3.mp4

when I click and move the cursor to the right ( X pixels to the right) the image first follow the cursor movement but at soon as I release the mouse click the image reload and appear to have displaced of -X to the left.
The  opposite is occurring for a click and move to the left, the image reload with a movement to the right 
The same bug is affecting the box zoom with a zoom out of the selected box.

when using `datashade=False` every thing is working as expected.

**Comment by maximlt** [comment]
This issue can be reproduced with the following snippet. The issue arises because the coordinates are descending, there's no issue when they're ascending. If only on dimension is ascending, the issue only happens in its direction. The issue doesn't appear with `rasterize=True` instead of `datashade=True`.

```python
import numpy as np
import xarray as xr
import hvplot.xarray

da = xr.DataArray(
    data=np.random.rand(1000, 1000),
    dims=['x', 'y'],
    coords={'x': np.arange(1000, 0, -1), 'y': np.arange(1000, 0, -1)}
)

da.hvplot(x='x', y='y', datashade=True)
```

I suspect this is related to https://github.com/holoviz/datashader/issues/1054

**Comment by maximlt** [comment]
I am very happy to report that this issue has been fixed upstream in datashader by https://github.com/holoviz/datashader/pull/1095

To get the fix in your environment you will need to install `datashader>=1.14.1`
