### ISSUE TITLE
Slow performance with hvplot and overlay

### ISSUE THREAD

**Issue by kearney-sp** [holoviz/hvplot#745]
I'm trying to make an app that overlays images with two features: (1) to toggle images on and off and (2) to be able to draw polygons over the images and then extract image data statistics that lie within the polygon.

I am able to make the features work, but performance is very slow whenever there are overlays (two or more images or just one image and a polygon). Performance is slow whether viewed in a Notebook or served with pn.serve().

Here is a reproducible example with a polygon overlayed on a single image. Note I get the same issue with two images overlayed and no polygons. I am running holoviews 1.14.6, hvplot 0.7.3, and xarray 0.20.1. (sorry if the syntax is odd, can't seem to get 'load code' to work..)

```python
# imports
import numpy as np
import xarray as xr
import holoviews as hv
import hvplot.xarray
import panel as pn

from holoviews import streams

# create fake image with name
da = xr.DataArray(data = np.array([np.random.randint(0, 100, 100) for i in range(100)]))
da.name = 'Data'

# create empty polygon for drawing
polys = hv.Polygons([])
max_polys = 1
poly_stream = streams.PolyDraw(source=polys, drag=True, num_objects=max_polys,
                                show_vertices=True)
edit_stream = streams.PolyEdit(source=polys, shared=True)

# create widget to toggle image visibility
bin_viz = pn.widgets.Checkbox(name='Visible', value=True)

# THIS IS FAST TO LOAD AND TOGGLE
m1 = da.hvplot.image(x='dim_0', y='dim_1',
          cmap='Inferno', clim=(0, 100), colorbar=False).apply.opts(visible=bin_viz.param.value)
pn.Row(bin_viz, m1)

# THIS IS 'SLOW' TO LOAD (2-3 SECONDS TO SHOW UP IN NOTEBOOK) AND TOGGLE (LAGS 1-2 SECONDS)
m1 = da.hvplot.image(x='dim_0', y='dim_1',
          cmap='Inferno', clim=(0, 100), colorbar=False).apply.opts(visible=bin_viz.param.value)
pn.Row(bin_viz, m1 * polys)
```

**Comment by maximlt** [comment]
Hi @kearney-sp, I've run your code and tried it directly in a notebook or with serving the app with `.show()` (see the GIF). It's pretty snappy!

![issue_hvplot_overlay_notslow](https://user-images.githubusercontent.com/35924738/166339468-a0af15cb-2431-4840-b42d-d6427c5354e1.gif)

I'm using the latest version of HoloViews and Panel, maybe you could try upgrading them?

**Comment by kearney-sp** [comment]
I'll try upgrading and report back - thanks @maximlt!

**Comment by kearney-sp** [comment]
Upgraded to holoviews 1.14.8, hvplot 0.7.3 (same as before) and xarray 2022.3.0 and confirm that the example is indeed snappy. In fact _everything_ is much snappier now! Thanks for the help.

**Comment by jbednar** [comment]
I have no idea why they would be faster except with bokeh version changes, but let's not complain!

**Comment by maximlt** [comment]
Thanks for your prompt feedback @kearney-sp, closing the issue then :)
