### ISSUE TITLE
Improve the API of the hvPlotExplorer

### ISSUE THREAD

**Issue by maximlt** [holoviz/hvplot#764]
There are mostly suggestions that occurred to me while writing the release blog post:

* by providing an easy entry point such as `hvplot.explore(df)` instead of having to instantiate the class `hvPlotExplorer`. I wasn't convinced by the name `hvPlotExplorer` either but it's fine if there's an easy and short entry point instead.
* by providing a way to get a handle on the plot. Should maybe get inspiration from `Interactive` that defines methods to get a handle of the various outputs it offers, such as `.widgets()`, `.panel()`, `.holoviews()`, etc.. Here I'd say I expect a `.plot()` method at least.

**Comment by maximlt** [comment]
Just noting that GeoPandas has a `.explore` method that returns an interactive Folium map: https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html

**Comment by jbednar** [comment]
I think it's fine for different libraries to have different `explore` functionality.

**Comment by MarcSkovMadsen** [comment]
For me `hvPlotExplorer` has the potential to provide quick BI like visualization of dataframes similar to what is possible with drag and drop in Power BI and Tableau. And furthermore the potential to autogenerate python code.

An updated name could be inspired by some kind of combination of `hvPlot`, `Data`, `DataFrame`, `Explorer`, `Chart`, `Editor`, `Maker`.

Its similar to

- https://www.highcharts.com/blog/products/highcharts-editor/
- https://www.trymito.io/
- https://chart-studio.plotly.com/create/#/

**Comment by maximlt** [comment]
Yes it's interesting because I think when I read `hvPlotExplorer` I understand that it is to explore data, while in practice I would more likely use that component to edit a plot. In that case I already have an idea of the kind of plot I want to get, it's just that the `.hvplot` API has so many parameters that building a plot from this component makes my life easier.

I remember seeing packages that offer a GUI to edit Matplotlib plots. Found one (not sure it's the one I was looking for) that does that: [plt-editor-tool](https://github.com/RichardCouperthwaite/plt-editor-tool). It has an accompanying user guide in PDF from which I've made this screenshot:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/35924738/175488426-1f97f7fd-10c9-492c-8467-6acb6f69b45e.png">

The advantage of `Explorer` is that it's general enough that it can be understood as *data* explorer and *hvPlot's API* explorer. I also quite like, or even prefer, `hvPlotEditor` (`hvplot.editor(df)`).

**Comment by jbednar** [comment]
I prefer `explorer` to `editor` for precisely the connotations that you mention above:

- editing is about tweaking an existing plot, with the expected input being an existing plot and the expected outcome of editing being an updated plot
- exploring is open-ended, starting with a dataset and _maybe_ resulting in a particular finished plot, but it may also simply result in the user now understanding the data and closing the explorer having achieved that understanding. 

This component takes in data, not an existing plot, so I think it should be called an explorer, reserving ".edit()" for something that accepts an existing plot object (which would be HoloViews, not hvPlot, by that point) and lets you tweak all of the options on it.

**Comment by maximlt** [comment]
Yes it will eventually be documented! Here's how you could start experimenting with it, by running this in a notebook:

```python
import pandas as pd
import numpy as np

from hvplot.ui import hvPlotExplorer
import hvplot.pandas

df = pd.DataFrame(np.random.rand(20, 2), columns=['a', 'b'])
hvPlotExplorer(df)
```
