### ISSUE TITLE
Add options for saving hvPlotExplorer settings and only show the plot

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/hvplot#787]
Maybe I have overlooked something, but it could be nice to be able to save the settings from `hvPlotExplorer` so it can easily be recreated in another session.  

I'm thinking about something like this:

``` python
## First input cell in a notebook
import hvplot.ui
import hvplot.pandas
import panel as pn
pn.extension()

from bokeh.sampledata import penguins

df = penguins.data
dfe = hvplot.ui.hvPlotExplorer(df)

## First output cell
# Play around with the Explorer until you have the plot you want

## Second input cell
dfe_settings = dfe.save()  # Returns a dict with the settings, which could be saved to a JSON file.

## Third input cell or another notebook where you have loaded the settings
# Load the settings into a new hvPlotExplorer
dfe2 = hvplot.ui.hvPlotExplorer.load(df, dfe_settings)
# or 
dfe2 = hvplot.ui.hvPlotExplorer(df, settings=dfe_settings)
```

Here a natural thing would be to only show the plot because all the settings have already been determined. Maybe with a function call like `dfe2.output()` or `dfe2.plot()`.

**Comment by jbednar** [comment]
Yes, definitely! To demo in the docs I think you'd use code like:

```python
# First notebook cell
settings = {}
if os.exists("somefile.json"):
    with open("settings.json") as f:
        settings = json.load(f)
dfe = hvplot.ui.hvPlotExplorer(df, **settings)

# Second notebook cell
with open("settings.json", 'w') as f:
    json.dump(settings, f)
```

That way the notebook will run properly the first time and when used with Run All, but when run cell-by-cell it will save the settings selected interactively for use next time.
