### ISSUE TITLE
Elevator pitch on homepage not up to date.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#802]
## Request

Update elevator pitch of hvPlot home page to  promote what hvPlot provides today.

## Motivation

HvPlot is very powerful. hvPlot is more than what it was when the original pitch was written. 

For example .interactive is not mentioned. 

I also believe that hvPlot as the easy entry point to the HoloViz ecosystem and the ability to drop into the rest of the HoloViz ecosystem should be mentioned.

If you are a Pandas data source user only (which a believe a lot of users would be) it should be very clear why hvPlot is still very usefull. It's not obvious from the text pitch that hvPlot provides more than what Pandas .plot or Plotly express already provides.

I believe inspiration can be found in the elevator pitch in https://github.com/holoviz/hvplot/pull/793 .

**Comment by maximlt** [comment]
I think this is better now with the new landing page added in hvPlot 0.8.0.
