### ISSUE TITLE
Add Gallery/ Topic notebooks to the `examples` folder

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#821]
I don't see the [Gallery/ Topic notebooks](https://hvplot.holoviz.org/topics.html) in the [examples folder](https://github.com/holoviz/hvplot/tree/master/examples) similarly to rest of HoloViz ecosystem. Please put them there to enable users to download and run all examples.

**Comment by maximlt** [comment]
Topics aren't generally found in the repo, they can link to other places such as examples.pyviz.org as it's the case for hvPlot and GeoViews (http://geoviews.org/topics.html). Topics really are open examples that use hvPlot. I'm not sure the name `Topics` mean much to anyone, maybe `Examples` or `Demos` would be better names.

Your request I believe is to add a Gallery to hvPlot, which is indeed missing. In my mind the gallery would be a collection of How-Tos.
