### ISSUE TITLE
Document hvplot.bind on website and with docstring

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#825]
I cannot find anything on website https://hvplot.holoviz.org/search.html?q=bind

![image](https://user-images.githubusercontent.com/42288570/183304108-431cb4f3-7e6c-4dc5-b42a-1410fe5ee47f.png)

And it has no docstring either.

**Comment by maximlt** [comment]
I am surprised the search did not return a better result. But `hvplot.bind` **is** documented here: https://hvplot.holoviz.org/user_guide/Interactive.html#functions-as-inputs

**Comment by MarcSkovMadsen** [comment]
I will close this issue. But someone should one day open an issue about the bad search results on the HoloViz sites. The search returns surprisingly few or irrelevant results.
