### ISSUE TITLE
hvplot.scatter_matrix width not fully working

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#84]
```
import pandas as pd
import hvplot.pandas

from bokeh.sampledata import iris, stocks 

iris = iris.flowers
hvplot.scatter_matrix(iris, c="species", width=500)
```
Doesn't adjust the center
![image](https://user-images.githubusercontent.com/15331990/46552203-d3da2400-c88e-11e8-88f2-aac1c2fd4f57.png)

Doesn't respond at all
```
hvplot.scatter_matrix(iris, c="species").options(width=500)
```

**Comment by talbertc-usgs** [comment]
The following commit partially fixes the issue.  

But the first column and last row of charts are  smaller.  Not sure why or where this is getting set, almost looks like the width/height variable includes the axes, ticks, labels, etc.

https://github.com/talbertc-usgs/hvplot/commit/89bc172b35b63573ebdf56fb7dce6308dc5d60f2

![image](https://user-images.githubusercontent.com/23191658/47735553-5ce83f00-dc32-11e8-8027-004f7da3b7d3.png)

![image](https://user-images.githubusercontent.com/23191658/47735568-6376b680-dc32-11e8-8600-bded5f6b54dc.png)

**Comment by jbednar** [comment]
Bokeh very often does include the axes, ticks, and labels in its calculations, and it takes a good bit of work to avoid that.  What I'm not sure is why this wouldn't have been a problem even without specifying width and height.

**Comment by philippjfr** [comment]
Internally HoloViews now uses `frame_width`/`frame_height` which ensures axes are taken into account.

**Comment by anitagraser** [comment]
Looks like in hvplot 0.8.3, neither width/height nor frame_width/frame_height result in the expected plots.

width/height has no effect:

![image](https://github.com/holoviz/hvplot/assets/590385/360e8f4a-19ac-4c38-8a80-ee51b2877d19)

frame_width/frame_height only resizes the scatter plots but not the histograms:

![image](https://github.com/holoviz/hvplot/assets/590385/d7eee744-8d84-4591-8a69-77b109e04a3e)

**Comment by Hoxbro** [comment]
> frame_width/frame_height only resizes the scatter plots but not the histograms

You should be able to use `hvplot.scatter_matrix(iris, c="species", frame_width=500, diagonal_kwds={"frame_width": 500})`.

Note that with the latest Bokeh there can be problem with alignment: https://github.com/holoviz/holoviews/issues/5784

**Comment by anitagraser** [comment]
Thank you, @Hoxbro. That works. I would have never found that solution.
