### ISSUE TITLE
Align casing of arguments to lower case

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#840]
A few arguments use upper case for some reason. As the lower case version 'c' is used often I would recommend simplifying to that one.

![image](https://user-images.githubusercontent.com/42288570/185805733-23204af5-e4f3-4b7d-8e5b-d2d83b9fd5d8.png)

**Comment by maximlt** [comment]
This is Panda's API: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.hexbin.html

**Comment by maximlt** [comment]
Pandas plotting doesn't have a heatmap method so I guess hvPlot's signature was in this case inspired from the hexbin signature. Maybe you could open an issue on Pandas' Github to try to see why they chose `C`?
