### ISSUE TITLE
Add "missing" data sources and plotting backends to the home page tabs

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#851]
Amazing new docs! https://pyviz-dev.github.io/hvplot/

The data sources section is really great for showing the power of hvPlot. Right now the purpose is to guide a single user that reads top to bottom. So Pandas is left out because its already mentioned.

![image](https://user-images.githubusercontent.com/42288570/186667305-6f5e53d8-bfb5-4848-bffd-e8fbdc8f3595.png)

But I believe it can also be used in a discussion with your team or as a screenshot or video on social media to show all the data sources that it works with. So I would really like to have Pandas included. And if others are missing (CuDF?) then get them added.

Similarly with the plotting backends. Please add Bokeh to the mix for completeness.

Thanks.

![image](https://user-images.githubusercontent.com/42288570/186667627-3fd66eea-bf17-4654-8aee-3a1db7b1c4b7.png)

**Comment by jbednar** [comment]
Very true! A PR would be very helpful!
