### ISSUE TITLE
Invalid url: http://www.ucrdatatool.gov/Search/Crime/State/StatebyState.cfm

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#870]
The url http://www.ucrdatatool.gov/Search/Crime/State/StatebyState.cfm in the datasets.yaml file is not valid. Neither is the https:// version.

![image](https://user-images.githubusercontent.com/42288570/187059949-55bee23b-9f2e-4708-bc96-0e3ada2e8bfb.png)

I've tried to find a replacement but was not able to.

**Comment by Hoxbro** [comment]
A quick search seems that the page has been moved to https://crime-data-explorer.app.cloud.gov.

The URL is only used for metadata and the data itself is located here: 'hvplot/examples/data/crime.csv'

**Comment by Hoxbro** [comment]
I will close this issue and let the discussion continue in #873.
