### ISSUE TITLE
Tooltips not working in area reference

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#875]
If I navigate to https://pyviz-dev.github.io/hvplot/reference/pandas/area.html and hover over any of the plots, I just get `???` instead of values.

![hover-not-working-hvplot](https://user-images.githubusercontent.com/42288570/187072218-1a6f26f3-e795-4e88-939c-7217e0ee7c6e.png)

**Comment by Hoxbro** [comment]
Duplicate of https://github.com/holoviz/holoviews/issues/5375
