### ISSUE TITLE
GridSpace axes not aligned when using `row`, or both `col` and `row` with outside legend

### ISSUE THREAD

**Issue by JanHomann** [holoviz/hvplot#927]
### Versions
```
hvplot      0.8.1
holoviews   1.15.1
panel       0.13.1

pandas      1.5.0
numpy       1.22.4
python      3.9.13
jupyterlab  3.4.5

Chrome Browser
```

### Description
Not 100% sure if this issue has been raised already (I did check). Having one or more legends outside of a plot tile in a `GridSpace`  constructed by hvplot by using the `row=` and / or `col=` argument screws up the alignment of the outer `GridSpace` axes in the case of `legend=right` (the default) or `legend=top`. 

Other, less severe inconsistencies: 
- There is too much horizontal space between the plots and the vertical GridSpace axis compared to the horizontal GridSpace axis. 
- The toolbar is, in one case, inside the GridSpace axis and, in other cases, outside (see screenshots). 
- One legend for all plots, like in seaborn, would be a nice feature.

### Example
```python
import pandas as pd
import numpy as np
import hvplot.pandas

# example DataFrame
df = pd.DataFrame(data=np.random.randn(20,8),
                  index=pd.Index(range(20), 
                                 name='ind0'),
                  columns=pd.MultiIndex.from_product([['lev0_a','lev0_b'],
                                                      ['lev1_a','lev1_b'],
                                                      ['lev2_a','lev2_b']], 
                                                     names=['lev0','lev1','lev2']) )

# reshape DataFrame for plotting
df = (df.stack(level=[0,1,2])
        .to_frame()
        .sort_index()
        .rename(columns={0:'col1'})
        .reset_index(level=[1,2,3]))
        
    
        
# plot DataFrame
p = df.hvplot.line(x='ind0',
                    y='col1', 
                    by=['lev2'], 
                    row='lev1', 
                    # col='lev0',   legend='top'    # uncomment: misaligns vertical GridSpace axis
                   ) 
p
```

### Screenshots
<img width="407" alt="Screen Shot 2022-10-09 at 7 58 58 PM" src="https://user-images.githubusercontent.com/35338267/194785452-3f38b2e7-2352-454c-a5ca-7c00683b861b.png">

<img width="329" alt="Screen Shot 2022-10-09 at 7 59 13 PM" src="https://user-images.githubusercontent.com/35338267/194785460-80f00d5e-4553-4efd-94ba-44b456f46771.png">

<img width="508" alt="Screen Shot 2022-10-09 at 7 59 36 PM" src="https://user-images.githubusercontent.com/35338267/194785467-2edb7204-d0db-45a1-b4b8-d54b860cb7bd.png">

**Comment by maximlt** [comment]
Hi @JanHomann, thanks for reporting that.

The first and main issue you report has already been reported in HoloViews (https://github.com/holoviz/holoviews/issues/5438). HoloViews' Github tracker is also a good place to find "hvPlot" issues. If you find one issue that is in HoloViews, don't hesitate to bump it so that we're aware it is causing you trouble.

Among the other issues that you report, `One legend for all plots, like in seaborn, would be a nice feature` actually seems like an hvPlot bug as HoloViews can display only one legend per grid space, as shown in the issue above. I'm going to open a dedicated issue for that, as it might as well fix the other smaller issues you reported.

**Comment by JanHomann** [comment]
Hi @maximlt, Thanks for pointing this out! I thought I had seen the issue somewhere. I searched in the hvplot GitHub but not in the holoviews GiitHub. 🤦‍♂️
